site_name: nand2mario
site_url: https://amichai-bd.github.io/nand2mario/
repo_url: https://github.com/amichai-bd/nand2mario
edit_uri: edit/main/
docs_dir: workdir/wiki/docs
site_dir: workdir/wiki/site
strict: true

theme:
  name: mkdocs

hooks:
  - tools/wiki/site.py
extra_javascript:
  - site-assets/toggle.js
extra_css:
  - site-assets/toggle.css

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
