"""Tagged, uncached host operations with private-safe packet summaries."""
from datetime import datetime, timezone
import json
import subprocess
import uuid

from .. import generated_interfaces as abi
from ..records import atomic_json, file_hash
from .client import Client, summary
from .package import read_package
from .transport import session


def run(root, build, args, provenance):
    folder = build / 'host' / args.action / uuid.uuid4().hex
    folder.mkdir(parents=True)
    report = {'status': 'FAIL', 'action': args.action, 'wire_abi': abi.WIRE_ABI,
              'profile': abi.PROFILE_NAME, **provenance}
    journal = folder / 'transactions.jsonl'
    def record(entry):
        with journal.open('a', encoding='utf-8') as stream:
            stream.write(json.dumps({'time': datetime.now(timezone.utc).isoformat(), **entry}, sort_keys=True) + '\n')
    try:
        image = None
        if args.action == 'load':
            image, report['package'] = read_package(root, args.package)
        if args.action == 'step' and not 1 <= args.dots <= abi.WIRE_STEP_MAX_DOTS:
            raise ValueError('step budget outside generated bounds')
        if args.action == 'input' and not 0 <= args.mask <= (1 << abi.INPUT_BYTES * 8) - 1:
            raise ValueError('input mask outside generated byte width')
        if args.action == 'write':
            from ..interface_codec import host_write
            host_write(args.address, args.value)
        # One repository-shared directory, including all linked author worktrees.
        common = subprocess.check_output(['git', '-C', str(root), 'rev-parse', '--path-format=absolute', '--git-common-dir'], text=True).strip()
        from pathlib import Path
        state_root = Path(common).parent / 'workdir/host-sessions'
        with session(folder, args, state_root) as (transport, sequence, persist, selected):
            client = Client(transport, sequence=sequence, record=record, persist=persist)
            report['endpoint'] = client.identify()
            if args.action == 'load':
                report['result'] = client.load(image)
            elif args.action == 'snapshot':
                metadata, pixels = client.snapshot()
                (folder / 'frame.2bpp').write_bytes(pixels)
                report['result'] = {'snapshot': metadata, 'pixels': summary(pixels)}
            elif args.action == 'write':
                report['result'] = client.write_host(args.address, args.value)
            elif args.action == 'status':
                # Do not read mutable split counters while the endpoint is running.
                report['result'] = {name: client.read_host(getattr(abi, 'HOST_REG_' + name))
                                    for name in ('STATE', 'IMAGE_VALID', 'PROFILE', 'INPUT')}
            else:
                value = args.dots if args.action == 'step' else args.mask if args.action == 'input' else None
                report['result'] = client.control(args.action.upper(), value)
        report['status'] = 'PASS'
    except Exception as error:
        report['error'] = str(error)
        record({'event': 'failure', 'reason': str(error)})
    report['artifacts'] = {path.relative_to(root).as_posix(): file_hash(path)
                           for path in folder.iterdir() if path.is_file()}
    atomic_json(folder / 'result.json', report)
    return report
