"""Tagged, uncached host operations with private-safe packet summaries."""
from datetime import datetime, timezone
from contextlib import ExitStack
import json
import subprocess
import uuid

from .. import generated_interfaces as abi
from ..records import atomic_json, file_hash
from .client import Client, summary
from .external import read_external
from .package import read_package
from .transport import open_serial, session


def run(root, build, args, provenance):
    folder = build / 'host' / args.action / uuid.uuid4().hex
    folder.mkdir(parents=True)
    report = {'status': 'FAIL', 'action': args.action, 'wire_abi': abi.WIRE_ABI,
              'profile': abi.PROFILE_NAME, **provenance}
    journal = folder / 'transactions.jsonl'
    client = None
    def record(entry):
        with journal.open('a', encoding='utf-8') as stream:
            stream.write(json.dumps({'time': datetime.now(timezone.utc).isoformat(), **entry}, sort_keys=True) + '\n')
    try:
        if args.action in ('crc-proof', 'keyboard'):
            import re
            if args.endpoint_restarted or not re.fullmatch('[0-9a-fA-F]{32}', args.expected_build_id):
                raise ValueError('operation requires a reviewed build ID and an already certain session')
        if args.action == 'keyboard' and args.json:
            raise ValueError('keyboard is an interactive console command; use its tagged result.json for records')
        image = None
        if args.action == 'load':
            if args.package:
                image, report['package'] = read_package(root, args.package)
            else:
                image, report['external'] = read_external(root, args.external)
        if args.action == 'step' and not 1 <= args.dots <= abi.WIRE_STEP_MAX_DOTS:
            raise ValueError('step budget outside generated bounds')
        if args.action == 'run-dots' and not 1 <= args.dots <= abi.WIRE_RUN_DOTS_MAX:
            raise ValueError('run count outside generated bounds')
        if args.action == 'input' and not 0 <= args.mask <= (1 << abi.INPUT_BYTES * 8) - 1:
            raise ValueError('input mask outside generated byte width')
        if args.action == 'write':
            from ..interface_codec import host_write
            host_write(args.address, args.value)
        # One repository-shared directory, including all linked author worktrees.
        common = subprocess.check_output(['git', '-C', str(root), 'rev-parse', '--path-format=absolute', '--git-common-dir'], text=True).strip()
        from pathlib import Path
        state_root = Path(common).parent / 'workdir/host-sessions'
        with ExitStack() as stack:
            if args.action == 'keyboard':
                from .console import Console
                from ci.storage import machine_lock
                console = stack.enter_context(Console())
                stack.enter_context(machine_lock(1357311510))
                def opener(port):
                    console.discard_pending()
                    if not console.focused():
                        raise RuntimeError('console lost foreground before serial open')
                    return open_serial(port)
                connection = session(folder, args, state_root, opener=opener)
            else:
                connection = session(folder, args, state_root)
            transport, sequence, persist, selected = stack.enter_context(connection)
            client = Client(transport, sequence=sequence, record=record, persist=persist)
            report['endpoint'] = client.identify()
            if args.action == 'keyboard':
                if report['endpoint']['build_id'] != args.expected_build_id.lower():
                    raise ValueError('keyboard build identity mismatch')
                from .keyboard import run as keyboard
                print('Release mapped keys before playing. Arrows: move; Z: A; X: B; right Shift: Select; Enter: Start. Escape/Ctrl+C: exit. Focus loss releases and exits.')
                console.discard_pending()
                try:
                    report['result'] = keyboard(client, console)
                finally:
                    report.update(sequence=client.sequence, uncertain=client.uncertain)
            elif args.action == 'crc-proof':
                if report['endpoint']['build_id'] != args.expected_build_id.lower():
                    raise ValueError('CRC proof build identity mismatch')
                from .crc_proof import run as crc_proof
                report['result'] = crc_proof(client)
            elif args.action == 'load':
                report['result'] = client.load(image)
            elif args.action == 'snapshot':
                metadata, pixels = client.snapshot()
                (folder / 'frame.2bpp').write_bytes(pixels)
                report['result'] = {'snapshot': metadata, 'pixels': summary(pixels)}
            elif args.action == 'write':
                report['result'] = client.write_host(args.address, args.value)
            elif args.action == 'status':
                # Do not read mutable split counters while the endpoint is running.
                report['result'] = {name: client.read_host(getattr(abi, 'HOST_REG_' + name))
                                    for name in ('STATE', 'IMAGE_VALID', 'PROFILE', 'INPUT')}
            elif args.action == 'io':
                # Live register reads. The endpoint is not paused or stepped.
                result = client.sample_io(args.samples)
                (folder / 'io_samples.json').write_text(json.dumps(result['samples'], indent=2), encoding='utf-8')
                report['result'] = {'samples': len(result['samples']), 'registers': result['registers'],
                                    'first': result['samples'][0], 'last': result['samples'][-1]}
            elif args.action == 'run-dots':
                report['result'] = client.run_dots(args.dots)
            else:
                value = args.dots if args.action == 'step' else args.mask if args.action == 'input' else None
                report['result'] = client.control(args.action.upper(), value)
        report['status'] = 'PASS'
    except Exception as error:
        report['error'] = str(error)
        record({'event': 'failure', 'reason': str(error)})
    except KeyboardInterrupt:
        if args.action != 'keyboard':
            raise
        report['error'] = 'keyboard interrupted'
        record({'event': 'failure', 'reason': report['error']})
    if args.action == 'keyboard' and client is not None:
        report.update(sequence=client.sequence, uncertain=client.uncertain)
    report['artifacts'] = {path.relative_to(root).as_posix(): file_hash(path)
                           for path in folder.iterdir() if path.is_file()}
    atomic_json(folder / 'result.json', report)
    return report
