; Complete 8x8 scene in the aligned shadow page; publisher remains shared.
SECTION "scene",ROM
PrepareScene:
LD DE,SceneBuffer
CALL SelectCourier
LD A,[PlayerX]
LD [ObjectX],A
LD A,[PlayerX+1]
LD [ObjectX+1],A
LD A,[PlayerY]
LD [ObjectY],A
LD A,[PlayerY+1]
LD [ObjectY+1],A
LD A,[Fell]
LD [SceneHidden],A
CALL ScenePosition
; Center approved 16-wide artwork on the existing 8-wide collision box.
LD A,[SceneBaseX]
SUB A,4
LD [SceneBaseX],A
LD A,[SceneBaseX+1]
SBC A,0
LD [SceneBaseX+1],A
CALL ComposeCourier
LD A,[EnemyX]
LD [ObjectX],A
LD A,[EnemyX+1]
LD [ObjectX+1],A
LD A,$80
LD [ObjectY],A
LD A,$07
LD [ObjectY+1],A
XOR A,A
LD [SceneHidden],A
LD A,16
LD [SceneTile],A
CALL AppendScene
LD A,$00
LD [ObjectX],A
LD A,$06
LD [ObjectX+1],A
LD A,$80
LD [ObjectY],A
LD A,$05
LD [ObjectY+1],A
LD A,[Collected]
AND A,1
LD [SceneHidden],A
LD A,18
LD [SceneTile],A
CALL AppendScene
LD A,$80
LD [ObjectX],A
LD A,$10
LD [ObjectX+1],A
LD A,$80
LD [ObjectY],A
LD A,$04
LD [ObjectY+1],A
LD A,[Collected]
AND A,2
LD [SceneHidden],A
LD A,18
LD [SceneTile],A
CALL AppendScene
LD A,$00
LD [ObjectX],A
LD A,$1D
LD [ObjectX+1],A
LD A,$80
LD [ObjectY],A
LD A,$05
LD [ObjectY+1],A
LD A,[Collected]
AND A,4
LD [SceneHidden],A
LD A,18
LD [SceneTile],A
CALL AppendScene
LD A,$00
LD [ObjectX],A
LD A,$29
LD [ObjectX+1],A
LD A,$00
LD [ObjectY],A
LD A,$05
LD [ObjectY+1],A
LD A,[Collected]
AND A,8
LD [SceneHidden],A
LD A,18
LD [SceneTile],A
CALL AppendScene
LD A,$00
LD [ObjectX],A
LD A,$2E
LD [ObjectX+1],A
LD A,$00
LD [ObjectY],A
LD A,$07
LD [ObjectY+1],A
XOR A,A
LD [SceneHidden],A
LD A,20
LD [SceneTile],A
CALL AppendScene
; Remaining OAM bytes are inactive; mode/score now belong to the BG HUD.
XOR A,A
ClearSceneTail:
LD [DE],A
INC DE
LD A,E
CP A,$A0
JR Z,SceneComplete
XOR A,A
JR ClearSceneTail
SceneComplete:
RET

AppendScene:
CALL ScenePosition
JP EmitPair

ScenePosition:
; Signed Q4 floor and full-width camera subtraction, before OAM wrapping.
LD A,[ObjectX]
LD L,A
LD A,[ObjectX+1]
LD H,A
CALL PixelFloor
LD A,[Camera]
LD C,A
LD A,[Camera+1]
LD B,A
LD A,L
SUB A,C
LD [SceneBaseX],A
LD A,H
SBC A,B
LD [SceneBaseX+1],A
LD A,[ObjectY]
LD L,A
LD A,[ObjectY+1]
LD H,A
CALL PixelFloor
LD A,L
LD [SceneBaseY],A
LD A,H
LD [SceneBaseY+1],A
RET

INCLUDE "oam_dma.asm"
INCLUDE "courier.asm"
