"""Bounded Cyclone V clock generation with the Altera PLL IP, and its fit evidence.

ALTPLL does not serve Cyclone V: `qmegawiz` refuses the family outright. The
Altera PLL IP takes its place, generated by `ip-generate` from the explicit
Quartus directory. It brings a different instance hierarchy, different port
names and a different fit-report shape, so this module owns the Cyclone V
generation command, the generated-HDL check and every report check; the
[clocking registry](fpga_clocking.py) selects it by the board's family.

The clock contract is unchanged: a 50 MHz reference, a 25 MHz system clock and a
25.2 MHz pixel clock (wiki/src/clocks-resets-cdc.md). The request states the
physical counters rather than a desired frequency, so the generated HDL states
the VCO frequency and the VCO post-scale divider itself and the checks read the
intended oscillator out of the design instead of inferring it from a report. The
fit report's M, N and C counters and the analysed clock periods are then checked
exactly, so the realized division is evidence and a different solution fails the
build.
"""
from collections import namedtuple
from fractions import Fraction
from pathlib import Path
import re

from .records import file_hash
from . import fpga_clocking, fpga_lock_cyclonev

TOOLS_KEY = "altera_pll"
FAMILY = "Cyclone V"
# The Cyclone V tops that carry generated clocks: the bounded clocking proof and
# the UART endpoint image that consumes the same two PLLs.
SUPPORTED_TOPS = ("nano_clocking_proof", "nano_uart_proof")
PIXEL_MODULE = "n2m_pixel_pll_cyclonev"
SYSTEM_MODULE = "n2m_system_pll_cyclonev"
# The fitted atom hierarchy the Fitter and the Timing Analyzer both name. A
# request that states the physical counters makes the IP instantiate its
# Cyclone V PLL directly, so the atoms sit under `cyclonev_pll` and carry that
# PLL's own names instead of the family-generic `general[0].gpll` ones.
SYSTEM_INSTANCE = "u_clocking|u_system_pll|altera_pll_i|cyclonev_pll"
PIXEL_INSTANCE = "u_clocking|u_pll|altera_pll_i|cyclonev_pll"
COUNTER_ATOM = "counter[0].output_counter"
FRACTIONAL_ATOM = "fpll_0|fpll"
SYSTEM_PLL = SYSTEM_INSTANCE + "|" + COUNTER_ATOM
PIXEL_PLL = PIXEL_INSTANCE + "|" + COUNTER_ATOM
SYSTEM_CLOCK = SYSTEM_PLL + "|divclk"
PIXEL_CLOCK = PIXEL_PLL + "|divclk"
SYSTEM_VCO = SYSTEM_INSTANCE + "|" + FRACTIONAL_ATOM + "|vcoph[0]"
PIXEL_VCO = PIXEL_INSTANCE + "|" + FRACTIONAL_ATOM + "|vcoph[0]"
SYSTEM_NET = "\\" + SYSTEM_INSTANCE + "|divclk[0]~CLKENA0_outclk"
# The generated wrapper instance each PLL is, as the synthesis report's port
# connectivity checks name it, and the Cyclone V PLL instance inside it that
# owns every fitted atom.
FIT_WRAPPERS = {SYSTEM_MODULE: ("n2m_clocking_cyclonev:u_clocking|n2m_system_pll_cyclonev:u_system_pll|"
                               "altera_pll:altera_pll_i"),
                PIXEL_MODULE: ("n2m_clocking_cyclonev:u_clocking|n2m_pixel_pll_cyclonev:u_pll|"
                               "altera_pll:altera_pll_i")}
FIT_PLL = "altera_cyclonev_pll:cyclonev_pll"
# The fit report names each atom by entity and instance, so its fractional PLL
# carries the enclosing base entity the Timing Analyzer's node name omits.
FIT_FRACTIONAL = "altera_cyclonev_pll_base:" + FRACTIONAL_ATOM
FIT_SYSTEM = FIT_WRAPPERS[SYSTEM_MODULE] + "|" + FIT_PLL + "|" + FIT_FRACTIONAL
FIT_PIXEL = FIT_WRAPPERS[PIXEL_MODULE] + "|" + FIT_PLL + "|" + FIT_FRACTIONAL
# The PLL VCO operating range this board's speed grade allows, in MHz. The
# fVCO row of the PLL Specifications table gives 600 to 1400 MHz for the -C7
# and -I7 speed grades, and 5CSEBA6U23I7 is -I7; wiki/src/de10-nano-board.md
# cites the datasheet.
VCO_RANGE_MHZ = (Fraction(600), Fraction(1400))
# The VCO post-scale divider is one bit, so K is 1 or 2 and nothing else.
POST_SCALE_VALUES = (1, 2)
# The physical configuration each PLL instance states. `multiply`, `divide` and
# `counter` are the M, N and C counters; `post_scale` is the VCO post-scale
# divider K; `charge_pump` and `bandwidth` are the loop filter settings the IP
# derives for that configuration. The generator is driven with the counters and
# the generated HDL must state all of it back, so the VCO is a recorded design
# fact and not a solver's choice. Both instances keep K at 1, so the oscillator
# and the figure every tool prints are the same number.
Configuration = namedtuple("Configuration", "multiply divide counter post_scale charge_pump bandwidth")
CONFIGURATION = {SYSTEM_MODULE: Configuration(26, 2, 26, 1, 20, 4000),
                 PIXEL_MODULE: Configuration(63, 5, 25, 1, 20, 6000)}
# The one definition this family supports; the pixel ratio and the system
# divider are the clock contract's, shared with the MAX 10 definition.
DEFINITION = {"module": PIXEL_MODULE, "input_ps": 20000, "multiply": 63, "divide": 125, "system_divide": 2}


def validate(definition):
    """The one supported definition, realized by an in-range, exact configuration.

    Every entry point validates, so a configuration whose VCO leaves the
    datasheet range or whose counters miss the contract's frequency refuses the
    build here, before any tool is launched.
    """
    if definition != DEFINITION:
        raise ValueError("unsupported PLL definition")
    low, high = VCO_RANGE_MHZ
    for module in (SYSTEM_MODULE, PIXEL_MODULE):
        # The post-scale divider is one bit of hardware: the IP allows 1 or 2 and
        # the datasheet footnote describes only those, so the oscillator can never
        # be more than twice the figure the tools print.
        if CONFIGURATION[module].post_scale not in POST_SCALE_VALUES:
            raise ValueError(f"unsupported PLL VCO post-scale divider: {module} states "
                             f"{CONFIGURATION[module].post_scale}, not 1 or 2")
        vco = physical_vco(module, definition)
        if not low <= vco <= high:
            raise ValueError(f"PLL VCO frequency outside the Cyclone V range: {module} runs at "
                             f"{float(vco):.6g} MHz, not {float(low):.6g} to {float(high):.6g} MHz")
        config = CONFIGURATION[module]
        if stated_vco(module, definition) / config.counter != frequencies(definition)[module]:
            raise ValueError("PLL configuration does not produce the contract frequency: " + module)


def physical_vco(module, definition=None):
    """The oscillator frequency in MHz the datasheet range bounds, as an exact ratio.

    The VCO post-scale divider K sits between the oscillator and the phase mux
    that feeds both the M feedback counter and the C output counters, so the
    frequency the IP states and the fit report prints is the oscillator divided
    by K. The datasheet says the same in the fVCO footnote: the reported figure
    takes K into account and can fall below the fVCO specification when K is 2.
    The range applies to the oscillator, so the check multiplies K back in.
    """
    config = CONFIGURATION[module]
    reference = frequencies(DEFINITION if definition is None else definition)["reference"]
    return reference * config.multiply * config.post_scale / config.divide


def stated_vco(module, definition=None):
    """The VCO figure the generated HDL states and the fit report prints: the oscillator over K."""
    return physical_vco(module, definition) / CONFIGURATION[module].post_scale


def frequencies(definition):
    """Requested reference, system and pixel frequencies in MHz, as exact ratios."""
    reference = Fraction(1_000_000, definition["input_ps"])
    return {"reference": reference,
            SYSTEM_MODULE: reference / definition["system_divide"],
            PIXEL_MODULE: reference * Fraction(definition["multiply"], definition["divide"])}


def generated_sources(definition):
    """The generated vendor HDL the project compiles, in a fixed order."""
    validate(definition)
    return [PIXEL_MODULE + ".v", SYSTEM_MODULE + ".v"]


def assignments(definition):
    """The PLL instance assignments the generated QIP states, written explicitly.

    The QIP is retained but never evaluated, so the compensation mode, the
    auto-reset setting and the bandwidth preset are declared here from this
    module's own constants. Without the compensation mode the Fitter warns that
    the PLL has no clock to compensate (Quartus 177007) and compensates every
    output; direct compensation is what the IP requests for `direct` operation.
    """
    validate(definition)
    lines = []
    for module in (PIXEL_MODULE, SYSTEM_MODULE):
        target = f'"*{module}*|altera_pll:altera_pll_i*|*"'
        for name, value in (("PLL_COMPENSATION_MODE", "DIRECT"), ("PLL_AUTO_RESET", "OFF"),
                            ("PLL_BANDWIDTH_PRESET", "AUTO")):
            lines.append(f"set_instance_assignment -name {name} {value} -to {target}")
    return lines


def cache_files(definition):
    """Generated HDL, generated QIP and generation log per PLL; reuse needs all of them."""
    validate(definition)
    return [name for module in (PIXEL_MODULE, SYSTEM_MODULE)
            for name in (module + ".v", module + ".qip", "generate-" + module + ".log")]


def identity(directory):
    """Hash the explicit Cyclone V PLL generation dependencies into the request."""
    directory = Path(directory).resolve()
    quartus = directory.parent
    component = quartus.parent / "ip/altera/altera_pll/source/top"
    paths = {"generator": quartus / "sopc_builder/bin/ip-generate",
             "definition": component / "pll_hw.tcl",
             "primitive": quartus / "libraries/megafunctions/altera_pll.v",
             "atom_model": quartus / "eda/sim_lib/cyclonev_atoms.v",
             "register_model": quartus / "eda/sim_lib/altera_primitives.v",
             "rules": component / "pll_hw_extra.tcl",
             "wizard": component / "pll_rbc.tcl"}
    if any(not path.is_file() for path in paths.values()):
        raise ValueError("missing explicit Quartus Altera PLL generation dependency")
    return {name: {"path": str(path), "sha256": file_hash(path)} for name, path in paths.items()}


def generation_command(identity, definition, module, device):
    validate(definition)
    if module not in (PIXEL_MODULE, SYSTEM_MODULE):
        raise ValueError("unsupported generated PLL module")
    if not isinstance(device, str) or not re.fullmatch(r"[A-Za-z0-9]+", device):
        raise ValueError("Cyclone V PLL generation requires the target device")
    config = CONFIGURATION[module]
    return [identity["generator"]["path"], "--component-name=altera_pll", f"--output-name={module}",
            "--file-set=QUARTUS_SYNTH", "--output-directory=.", f"--report-file=qip:{module}.qip",
            f"--component-parameter=gui_reference_clock_frequency={float(frequencies(definition)['reference']):.1f}",
            "--component-parameter=gui_number_of_clocks=1",
            # The physical counters, not a desired frequency: the IP then states
            # the VCO and its post-scale divider instead of solving for them.
            "--component-parameter=gui_en_adv_params=1",
            f"--component-parameter=gui_multiply_factor={config.multiply}",
            f"--component-parameter=gui_divide_factor_n={config.divide}",
            f"--component-parameter=gui_divide_factor_c0={config.counter}",
            "--component-parameter=gui_use_locked=1",
            "--component-parameter=gui_operation_mode=direct",
            f"--part={device}", f"--system-info=DEVICE_FAMILY={FAMILY}"]


def generate(folder, identity, definition, execute, timeout, record, build, *, device=None):
    for module in (PIXEL_MODULE, SYSTEM_MODULE):
        log = folder / ("generate-" + module + ".log")
        execute(generation_command(identity, definition, module, device), folder, log, timeout, record, build)
        _verify_log(log, module)
    verify(folder, definition)


def _verify_log(log, module):
    """The generator reported an implementable PLL and exactly its two files.

    `ip-generate` prefixes every line with a timestamp, so the builder's
    line-anchored diagnostic classifier cannot see its messages; this reads them.
    """
    text = log.read_text(encoding="utf-8", errors="replace")
    diagnostics = re.findall(r"(?m)^\S+\s+(?:Error|Critical Warning|Warning):.*$", text)
    if diagnostics:
        raise ValueError("Cyclone V PLL generator diagnostic: " + diagnostics[0].strip())
    for expected in (f"{module}: Able to implement PLL with user settings",
                     f'{module}: Done "{module}" with 1 modules, 2 files'):
        if expected not in text:
            raise ValueError("Cyclone V PLL generation is not the checked result: " + expected)


def verify(folder, definition=None):
    """Every generated PLL states exactly the requested vendor parameters."""
    definition = DEFINITION if definition is None else definition
    validate(definition)
    for module in (PIXEL_MODULE, SYSTEM_MODULE):
        _verify_module(folder, definition, module)


def _counter_halves(name, value, index=""):
    """One divider's stated parameters: its two half-periods, bypass and odd duty.

    A Cyclone V counter is programmed as its high and low half-period counts, so
    an odd divide splits unevenly and sets the odd-duty enable, and a divide of
    one bypasses the counter with both halves parked at their maximum.
    """
    if value == 1:
        high, low, bypass, odd = 256, 256, "true", "false"
    else:
        high, low, bypass = (value + 1) // 2, value // 2, "false"
        odd = "true" if value % 2 else "false"
    return {f"{name}_hi_div{index}": str(high), f"{name}_lo_div{index}": str(low),
            f"{name}_bypass_en{index}": f'"{bypass}"', f"{name}_odd_div_duty_en{index}": f'"{odd}"'}


def _verify_module(folder, definition, module):
    path = folder / (module + ".v")
    text = path.read_text(encoding="utf-8")
    values = frequencies(definition)
    config = CONFIGURATION[module]
    expected = {"fractional_vco_multiplier": '"false"',
                "reference_clock_frequency": f'"{float(values["reference"]):.1f} MHz"',
                "pll_fractional_cout": "32", "pll_dsm_out_sel": '"1st_order"',
                "operation_mode": '"direct"', "number_of_clocks": "1",
                "output_clock_frequency0": f'"{float(values[module]):.6f} MHz"',
                "phase_shift0": '"0 ps"', "duty_cycle0": "50",
                "pll_type": '"Cyclone V"', "pll_subtype": '"General"',
                # The VCO this design states, its post-scale divider and the loop
                # filter the IP derives for them. physical_vco explains the two
                # frequencies; the datasheet range is checked in validate.
                "pll_output_clk_frequency": f'"{float(stated_vco(module, definition)):.1f} MHz"',
                "pll_vco_div": str(config.post_scale),
                "pll_cp_current": str(config.charge_pump), "pll_bwctrl": str(config.bandwidth),
                "pll_fractional_division": '"1"', "mimic_fbclk_type": '"none"',
                "pll_fbclk_mux_1": '"glb"', "pll_fbclk_mux_2": '"m_cnt"',
                "pll_m_cnt_in_src": '"ph_mux_clk"', "pll_slf_rst": '"false"'}
    expected.update(_counter_halves("m_cnt", config.multiply))
    expected.update(_counter_halves("n_cnt", config.divide))
    expected.update(_counter_halves("c_cnt", config.counter, index=0))
    expected.update({"c_cnt_prst0": "1", "c_cnt_ph_mux_prst0": "0", "c_cnt_in_src0": '"ph_mux_clk"'})
    # Every other output must be off, so the instance carries exactly one clock.
    for index in range(1, 18):
        expected[f"output_clock_frequency{index}"] = '"0 MHz"'
        expected[f"phase_shift{index}"] = '"0 ps"'
        expected[f"duty_cycle{index}"] = "50"
        expected.update({f"c_cnt_hi_div{index}": "1", f"c_cnt_lo_div{index}": "1",
                         f"c_cnt_prst{index}": "1", f"c_cnt_ph_mux_prst{index}": "0",
                         f"c_cnt_in_src{index}": '"ph_mux_clk"', f"c_cnt_bypass_en{index}": '"true"',
                         f"c_cnt_odd_div_duty_en{index}": '"false"'})
    for key, value in expected.items():
        found = re.findall(r"\.\s*" + key + r"\s*\(\s*([^,()]*?)\s*\)", text)
        if found != [value]:
            raise ValueError(f"generated PLL parameter mismatch: {key}")
    if re.search(r'`include\b|\$(?:readmemh|readmemb|fopen)\b', text):
        raise ValueError("untracked generated PLL dependency")
    if not re.search(r"module\s+" + re.escape(module) + r"\s*\(", text):
        raise ValueError("generated PLL module mismatch")
    ports = re.findall(r"(?m)^\s*(input|output)\s+wire\s+(\w+)\s*,?\s*$", text)
    if ports != [("input", "refclk"), ("input", "rst"), ("output", "outclk_0"), ("output", "locked")]:
        raise ValueError("generated PLL ports differ")
    if not re.search(r"\)\s*altera_pll_i\s*\(", text):
        raise ValueError("generated PLL instance name differs")


CONNECTIVITY_WARNING = "Warning (12241): 2 hierarchies have connectivity warnings - see the Connectivity Checks report folder"
SYNTHESIS_WARNING = "Warning (330000): Timing-Driven Synthesis is skipped because it could not initialize the timing netlist"
# The optional Altera PLL ports the generated wrapper leaves unconnected, with
# the severity the connectivity check gives each one.
CONNECTIVITY_PORTS = {
    ("fboutclk", "Output", "Info"): "Explicitly unconnected",
    ("fbclk", "Input", "Info"): "Stuck at GND",
    **{(name, "Input", "Warning"): "Declared by entity but not connected by instance. If a default value exists, it will be used.  Otherwise, the port will be connected to GND."
       for name in ("refclk1", "phase_en", "updn", "num_phase_shifts", "scanclk", "cntsel",
                    "reconfig_to_pll", "extswitch", "adjpllin", "cclk")},
    **{(name, kind, "Warning"): "Declared by entity but not connected by instance. Logic that only feeds a dangling port will be removed."
       for name, kind in (("phase_done", "Output"), ("reconfig_from_pll", "Output"), ("activeclk", "Output"),
                          ("clkbad", "Output"), ("phout", "Output"), ("lvds_clk", "Output"), ("loaden", "Output"),
                          ("extclk_out", "Output"), ("cascade_out", "Output"), ("zdbfbclk", "Bidir"))},
}


# The vendor PLL wrappers' outputs that the Cyclone V general-purpose branch
# never drives: LVDS, external clock and, for `clkout[0]`, the DLL. Each carries
# the vendor file and line that declares it inside the message body, so a
# different port, file or line there is a different diagnostic and fails.
UNDRIVEN_PORTS = (("clkout[0]", "altera_cyclonev_pll.v", 637), ("extclk", "altera_cyclonev_pll.v", 632),
                  ("loaden", "altera_cyclonev_pll.v", 641), ("lvdsclk", "altera_cyclonev_pll.v", 642),
                  ("lvds_clk", "altera_pll.v", 320), ("loaden", "altera_pll.v", 321),
                  ("extclk_out", "altera_pll.v", 322))
# The dynamic-phase-shift counter select tie-off the wrapper builds and synthesis
# then removes, one set per PLL instance.
REMOVED_NODES = tuple(f"cntsel_temp[{index}]" for index in range(5)) + ("gnd",)
REMOVED_HEADERS = {"14284": "Warning (14284): Synthesized away the following node(s):",
                   "14285": "Warning (14285): Synthesized away the following LCELL buffer node(s):"}
# Every diagnostic code this family's clocking explains. A code outside this set
# reaches the builder's own classifier and fails the build.
EXPLAINED_CODES = ("12241", "330000", "10034", "12030", "14284", "14285", "14320")
UNDRIVEN_REASON = ("An output of the vendor PLL wrapper that its Cyclone V general-purpose branch does not drive: "
                   "the LVDS, external-clock and DLL outputs this configuration does not use. The generated "
                   "wrapper leaves every one of them unconnected, which the synthesis connectivity report states "
                   "independently, so no net in the design reads an undriven port.")
DANGLING_REASON = ("The vendor's own wrapper connects a one-bit net to the Cyclone V PLL's two-bit external clock "
                   "port. That port is itself undriven and unconnected in the generated wrapper, so the dangling "
                   "bit reaches nothing.")
REMOVED_REASON = ("The counter-select tie-off the wrapper builds for dynamic phase shifting, removed because this "
                  "configuration has no reconfiguration ports; the connectivity report shows `cntsel` unconnected.")


def explained_diagnostics(text, folder, definition):
    """Explain every Cyclone V clocking diagnostic, each against its own evidence.

    12241 counts the generated wrapper's unconnected optional Altera PLL ports.
    It is accepted only after the synthesis report's two port connectivity
    tables are found to name exactly the two PLL instances and exactly the
    optional ports the wrapper leaves open.

    330000 is the cost of the checked endpoint collections: they name the
    generated PLL output clocks, which exist in the Fitter and Timing Analyzer
    netlists but not in the pre-synthesis one, so Analysis & Synthesis cannot
    initialize a timing netlist and skips timing-driven synthesis. The Fitter
    and the Timing Analyzer read the same constraints where those clocks do
    exist; the retained four-corner slack is the timing evidence.

    10034, 12030, 14284, 14285 and 14320 come with stating the physical
    counters: the IP then instantiates its Cyclone V PLL directly, and that
    branch leaves the LVDS, external-clock and DLL outputs undriven, mis-sizes
    its own external clock connection and ties off the unused phase-shift
    selects. Each port and node is named exactly, twice over for the two PLL
    instances, and the same connectivity report shows those wrapper ports
    unconnected, so none of them reaches the design.
    """
    validate(definition)
    lines = [line.strip() for line in text.splitlines()
             if line.strip().startswith(tuple(f"Warning ({code}):" for code in EXPLAINED_CODES))]
    if not lines:
        return []
    explained = []
    for code in EXPLAINED_CODES:
        found = [line for line in lines if line.startswith(f"Warning ({code}):")]
        explained += _explain_code(code, found)
    if len(explained) != len(lines):
        raise ValueError("Cyclone V clocking diagnostic identity or count differs")
    _verify_connectivity(folder)
    return explained


def _explain_code(code, lines):
    """Explain one diagnostic code's lines, or refuse them.

    Every message must be one this family predicts, and the count must be
    exactly what the two PLL instances produce.
    """
    if code in ("12241", "330000"):
        expected = CONNECTIVITY_WARNING if code == "12241" else SYNTHESIS_WARNING
        reason = ("The generated Altera PLL wrapper leaves the IP's optional reconfiguration, feedback and "
                  "secondary-output ports unconnected; the synthesis report names exactly those ports on "
                  "exactly the two PLL instances.") if code == "12241" else (
                 "The checked endpoint collections name the generated PLL output clocks, which exist only "
                 "after synthesis; the Fitter and the Timing Analyzer read them against netlists that carry "
                 "those clocks, and the four-corner slack is retained.")
        if lines != [expected]:
            raise ValueError("Cyclone V clocking diagnostic identity or count differs: " + code)
        return [{"code": code, "text": expected, "reason": reason}]
    if code in REMOVED_HEADERS:
        if lines != [REMOVED_HEADERS[code]]:
            raise ValueError("Cyclone V clocking diagnostic identity or count differs: " + code)
        return [{"code": code, "text": lines[0], "reason": REMOVED_REASON}]
    if code == "10034":
        wanted = {f'Output port "{port}" at {source}({line}) has no driver': 2
                  for port, source, line in UNDRIVEN_PORTS}
        return _explain_lines(code, lines, wanted, UNDRIVEN_REASON)
    if code == "12030":
        wanted = {('Port "extclk" on the entity instantiation of "cyclonev_pll" is connected to a signal of '
                   "width 1. The formal width of the signal in the module is 2.  The extra bits will be left "
                   "dangling without any fan-out logic."): 2}
        return _explain_lines(code, lines, wanted, DANGLING_REASON)
    if code != "14320":
        raise ValueError("no Cyclone V clocking explanation for diagnostic " + code)
    wanted = {f'Synthesized away node "{wrapper}|{node}"': 1
              for wrapper in FIT_WRAPPERS.values() for node in REMOVED_NODES}
    return _explain_lines(code, lines, wanted, REMOVED_REASON)


def _explain_lines(code, lines, wanted, reason):
    """Bind each message body to its expected count, allowing the vendor file suffix.

    The suffix carries the installed Quartus path, so it is matched by shape and
    never by value; the port, node, file and line in the body are exact.
    """
    counts = {}
    for line in lines:
        body = line.removeprefix(f"Warning ({code}): ")
        match = next((key for key in wanted if body == key or body.startswith(key + " File: ")), None)
        if match is None:
            raise ValueError(f"unpredicted Cyclone V clocking diagnostic {code}: {body}")
        counts[match] = counts.get(match, 0) + 1
    if counts != wanted:
        raise ValueError("Cyclone V clocking diagnostic identity or count differs: " + code)
    return [{"code": code, "text": line, "reason": reason} for line in lines]


def _connectivity_tables(report):
    """Every port connectivity table in the synthesis report, by owning instance."""
    tables = {}
    owner = None
    for line in report.splitlines():
        heading = re.fullmatch(r'; Port Connectivity Checks: "([^"]+)"\s*;\s*', line)
        if heading:
            owner = heading[1]
            if owner in tables:
                raise ValueError("duplicate connectivity check owner")
            tables[owner] = {}
            continue
        if owner is None:
            continue
        cells = [cell.strip() for cell in line.split(";")[1:-1]]
        if len(cells) == 4 and cells[0] not in ("Port", ""):
            tables[owner][(cells[0], cells[1], cells[2])] = cells[3]
        elif tables[owner] and line.startswith("+--"):
            owner = None
    return tables


def _verify_connectivity(folder):
    """Only the two generated PLL wrappers may carry a connectivity warning.

    Any other instance's table is accepted only when every row is informational:
    an unconnected diagnostic output or a constant-driven input of the product
    RTL, which the 12241 message's own hierarchy count corroborates.
    """
    report = (folder / "output/design.map.rpt").read_text(encoding="cp1252")
    tables = _connectivity_tables(report)
    warned = sorted(owner for owner, rows in tables.items()
                    if any(severity == "Warning" for _, _, severity in rows))
    if warned != sorted(FIT_WRAPPERS.values()):
        raise ValueError("connectivity check owners differ")
    for owner in warned:
        if tables[owner] != CONNECTIVITY_PORTS:
            raise ValueError("connectivity check port set or severity differs")
    for owner, rows in tables.items():
        if owner not in warned and any(severity != "Info" for _, _, severity in rows):
            raise ValueError("connectivity check severity differs: " + owner)


def clock_inventory(definition, reference):
    """Every STA clock row: name -> (kind, period, [duty, divide, multiply], master).

    Each PLL contributes its VCO clock and the output counter clock it divides.
    """
    rows = {"clk_reference": ("Base", reference, None, None)}
    for module, vco, output in ((SYSTEM_MODULE, SYSTEM_VCO, SYSTEM_CLOCK),
                                (PIXEL_MODULE, PIXEL_VCO, PIXEL_CLOCK)):
        multiply, divide, counter = CONFIGURATION[module][:3]
        rows[vco] = ("Generated", reference * divide / multiply,
                     ["50.00", str(divide), str(multiply)], "clk_reference")
        rows[output] = ("Generated", reference * divide * counter / multiply,
                        ["50.00", str(counter), "1"], vco)
    return rows


def corner_slacks(target, corner):
    """The clock names each timing corner must also carry, beyond the checked clocks.

    Only the VCO clocks: they have a minimum pulse width check and no data paths.
    """
    return [f"{corner} Model Minimum Pulse Width '{name}'" for name in (SYSTEM_VCO, PIXEL_VCO)]


def timed_clocks(target):
    """The clocks every corner and check must report, in the order they are named."""
    return ("clk_reference", SYSTEM_CLOCK, PIXEL_CLOCK)


def lock_event_count(target):
    """Cyclone V has no vendor lock latch, so no register may lack a clock."""
    return 0


def verify_lock_event(folder, checks, top="nano_clocking_proof", *, parallel=False, extra_rows=()):
    if not parallel or extra_rows or top not in SUPPORTED_TOPS:
        raise ValueError("unsupported Cyclone V clocking composition")
    return fpga_lock_cyclonev.verify((folder / "simulation/questa/design.vo").read_text(encoding="utf-8"), checks, top)


# The fit report carries a degree sign in its junction temperature rows; the
# registry owns that encoding fact so both families cannot drift apart.
FIT_ENCODING = fpga_clocking.FIT_ENCODING
FIT_EXPECTED = {
    "PLL Type": "Integer PLL", "PLL Feedback clock type": "none", "PLL Bandwidth": "Auto",
    "Reference Clock Frequency": "50.0 MHz", "Reference Clock Sourced by": "Dedicated Pin",
    "PLL Operation Mode": "Direct", "PLL Enable": "On", "PLL Fractional Division": "N/A",
    "IOPLL Self RST": "Off", "CLKIN(0) source": "clk_reference~input",
    "Duty Cycle": "50.0000", "Phase Shift": "0.000000 degrees",
    "C Counter PH Mux PRST": "0", "C Counter PRST": "1",
}


def verify_fit(folder, target):
    """Bind each fitted PLL to its wrapper instance, its counters and its clocks."""
    validate(target["pll"])
    report = (folder / "output/design.fit.rpt").read_text(encoding=FIT_ENCODING)
    blocks = _usage_blocks(report)
    if sorted(blocks) != sorted((FIT_SYSTEM, FIT_PIXEL)):
        raise ValueError("fitted PLL owners differ")
    for owner, module in ((FIT_SYSTEM, SYSTEM_MODULE), (FIT_PIXEL, PIXEL_MODULE)):
        multiply, divide, counter = CONFIGURATION[module][:3]
        values = frequencies(target["pll"])
        expected = {**FIT_EXPECTED, "M Counter": str(multiply), "N Counter": str(divide),
                    "C Counter": str(counter),
                    "PLL VCO Frequency": _megahertz(stated_vco(module, target["pll"])),
                    "Output Clock Frequency": _megahertz(values[module]),
                    "C Counter Odd Divider Even Duty Enable": "On" if counter % 2 else "Off"}
        for key, value in expected.items():
            if blocks[owner].get(key) != value:
                raise ValueError(f"fitted PLL configuration differs: {key}")
        if blocks[owner].get("PLL Output Counter") != FIT_WRAPPERS[module] + "|" + FIT_PLL + "|" + COUNTER_ATOM:
            raise ValueError("fitted PLL output counter owner differs")
    summary = (folder / "output/design.fit.summary").read_text(encoding="utf-8")
    if re.findall(r"(?m)^Total PLLs : (\d+) /", summary) != ["2"]:
        raise ValueError("fitted PLL physical resource count differs")
    _verify_clocks(folder, target)
    fpga_clocking.verify_reports(folder, "Cyclone V reset chain path missing or violated")


def _megahertz(value):
    """The fit report's frequency form: one decimal, trailing zero kept."""
    return f"{float(value):.1f} MHz"


def _usage_blocks(report):
    """The PLL Usage Summary as {fitted PLL name: {key: value}}.

    The section indents each key with dashes under the PLL it belongs to, and
    nests the output counter's rows under its own name; that name is kept as the
    `PLL Output Counter` value so its owner is checked too.
    """
    start = report.index("; PLL Usage Summary")
    end = report.index("Fitter Resource Utilization by Entity", start)
    blocks = {}
    current = None
    for line in report[start:end].splitlines():
        cells = [cell.strip() for cell in line.split(";")[1:-1]]
        if len(cells) != 2 or not cells[0] or cells[0] == "PLL Usage Summary":
            continue
        key, value = cells
        if not key.startswith("--"):
            current = blocks.setdefault(key, {})
            continue
        if current is None:
            raise ValueError("PLL usage row without an owner")
        key = key.lstrip("- ")
        if key.endswith("|" + COUNTER_ATOM):
            key, value = "PLL Output Counter", key
        elif not value:
            # A section label such as "PLL Refclk Select"; its rows follow.
            continue
        if key in current and current[key] != value:
            raise ValueError("duplicate PLL usage row: " + key)
        current[key] = value
    return blocks


def _verify_clocks(folder, target):
    sta = (folder / "output/design.sta.rpt").read_text(encoding="utf-8")
    rows = [[cell.strip() for cell in line.split(";")[1:-1]] for line in sta.splitlines()
            if re.match(r";[^;]+;\s*(?:Base|Generated)\s*;", line)]
    reference = Fraction(target["timing"]["reference_ns"])
    wanted = clock_inventory(target["pll"], reference)
    if len(rows) != len(wanted) or {row[0] for row in rows} != set(wanted):
        raise ValueError("Cyclone V clock inventory differs")
    for row in rows:
        kind, period, ratio, master = wanted[row[0]]
        if row[1] != kind or abs(float(row[2]) - float(period)) >= 0.001:
            raise ValueError("Cyclone V clock period differs: " + row[0])
        if ratio is not None and (row[6:9] != ratio or row[14] != master):
            raise ValueError("Cyclone V clock relationship differs: " + row[0])
