"""Bounded Cyclone V clock generation with the Altera PLL IP, and its fit evidence.

ALTPLL does not serve Cyclone V: `qmegawiz` refuses the family outright. The
Altera PLL IP takes its place, generated by `ip-generate` from the explicit
Quartus directory. It brings a different instance hierarchy, different port
names and a different fit-report shape, so this module owns the Cyclone V
generation command, the generated-HDL check and every report check; the
[clocking registry](fpga_clocking.py) selects it by the board's family.

The clock contract is unchanged: a 50 MHz reference, a 25 MHz system clock and a
25.2 MHz pixel clock (wiki/src/clocks-resets-cdc.md). The request states those
frequencies and the IP solves the physical counters; the fit report's M, N and C
counters and the analysed clock periods are then checked exactly, so the realized
division is evidence and a different solution fails the build.
"""
from fractions import Fraction
from pathlib import Path
import re

from .records import file_hash
from . import fpga_clocking, fpga_lock_cyclonev

TOOLS_KEY = "altera_pll"
FAMILY = "Cyclone V"
# Only the bounded Cyclone V clocking proof carries generated clocks today.
SUPPORTED_TOPS = ("nano_clocking_proof",)
PIXEL_MODULE = "n2m_pixel_pll_cyclonev"
SYSTEM_MODULE = "n2m_system_pll_cyclonev"
# The fitted atom hierarchy the Fitter and the Timing Analyzer both name.
SYSTEM_PLL = "u_clocking|u_system_pll|altera_pll_i|general[0].gpll~PLL_OUTPUT_COUNTER"
PIXEL_PLL = "u_clocking|u_pll|altera_pll_i|general[0].gpll~PLL_OUTPUT_COUNTER"
SYSTEM_CLOCK = SYSTEM_PLL + "|divclk"
PIXEL_CLOCK = PIXEL_PLL + "|divclk"
SYSTEM_VCO = "u_clocking|u_system_pll|altera_pll_i|general[0].gpll~FRACTIONAL_PLL|vcoph[0]"
PIXEL_VCO = "u_clocking|u_pll|altera_pll_i|general[0].gpll~FRACTIONAL_PLL|vcoph[0]"
SYSTEM_NET = r"\u_clocking|u_system_pll|altera_pll_i|outclk_wire[0]~CLKENA0_outclk"
# The fitted PLL block each usage-summary column belongs to, by wrapper instance.
FIT_SYSTEM = ("n2m_clocking_cyclonev:u_clocking|n2m_system_pll_cyclonev:u_system_pll|"
              "altera_pll:altera_pll_i|general[0].gpll~FRACTIONAL_PLL")
FIT_PIXEL = ("n2m_clocking_cyclonev:u_clocking|n2m_pixel_pll_cyclonev:u_pll|"
             "altera_pll:altera_pll_i|general[0].gpll~FRACTIONAL_PLL")
# The counters Quartus solves for each requested output, and the VCO they imply.
# multiply/divide/output-divide, as the fit report's M, N and C counters.
COUNTERS = {SYSTEM_MODULE: (12, 2, 12), PIXEL_MODULE: (63, 5, 25)}
# The one definition this family supports; the pixel ratio and the system
# divider are the clock contract's, shared with the MAX 10 definition.
DEFINITION = {"module": PIXEL_MODULE, "input_ps": 20000, "multiply": 63, "divide": 125, "system_divide": 2}


def validate(definition):
    if definition != DEFINITION:
        raise ValueError("unsupported PLL definition")


def frequencies(definition):
    """Requested reference, system and pixel frequencies in MHz, as exact ratios."""
    reference = Fraction(1_000_000, definition["input_ps"])
    return {"reference": reference,
            SYSTEM_MODULE: reference / definition["system_divide"],
            PIXEL_MODULE: reference * Fraction(definition["multiply"], definition["divide"])}


def generated_sources(definition):
    """The generated vendor HDL the project compiles, in a fixed order."""
    validate(definition)
    return [PIXEL_MODULE + ".v", SYSTEM_MODULE + ".v"]


def assignments(definition):
    """The PLL instance assignments the generated QIP states, written explicitly.

    The QIP is retained but never evaluated, so the compensation mode, the
    auto-reset setting and the bandwidth preset are declared here from this
    module's own constants. Without the compensation mode the Fitter warns that
    the PLL has no clock to compensate (Quartus 177007) and compensates every
    output; direct compensation is what the IP requests for `direct` operation.
    """
    validate(definition)
    lines = []
    for module in (PIXEL_MODULE, SYSTEM_MODULE):
        target = f'"*{module}*|altera_pll:altera_pll_i*|*"'
        for name, value in (("PLL_COMPENSATION_MODE", "DIRECT"), ("PLL_AUTO_RESET", "OFF"),
                            ("PLL_BANDWIDTH_PRESET", "AUTO")):
            lines.append(f"set_instance_assignment -name {name} {value} -to {target}")
    return lines


def cache_files(definition):
    """Generated HDL, generated QIP and generation log per PLL; reuse needs all of them."""
    validate(definition)
    return [name for module in (PIXEL_MODULE, SYSTEM_MODULE)
            for name in (module + ".v", module + ".qip", "generate-" + module + ".log")]


def identity(directory):
    """Hash the explicit Cyclone V PLL generation dependencies into the request."""
    directory = Path(directory).resolve()
    quartus = directory.parent
    component = quartus.parent / "ip/altera/altera_pll/source/top"
    paths = {"generator": quartus / "sopc_builder/bin/ip-generate",
             "definition": component / "pll_hw.tcl",
             "primitive": quartus / "libraries/megafunctions/altera_pll.v",
             "atom_model": quartus / "eda/sim_lib/cyclonev_atoms.v",
             "register_model": quartus / "eda/sim_lib/altera_primitives.v",
             "rules": component / "pll_hw_extra.tcl",
             "wizard": component / "pll_rbc.tcl"}
    if any(not path.is_file() for path in paths.values()):
        raise ValueError("missing explicit Quartus Altera PLL generation dependency")
    return {name: {"path": str(path), "sha256": file_hash(path)} for name, path in paths.items()}


def generation_command(identity, definition, module, device):
    validate(definition)
    if module not in (PIXEL_MODULE, SYSTEM_MODULE):
        raise ValueError("unsupported generated PLL module")
    if not isinstance(device, str) or not re.fullmatch(r"[A-Za-z0-9]+", device):
        raise ValueError("Cyclone V PLL generation requires the target device")
    output = frequencies(definition)[module]
    return [identity["generator"]["path"], "--component-name=altera_pll", f"--output-name={module}",
            "--file-set=QUARTUS_SYNTH", "--output-directory=.", f"--report-file=qip:{module}.qip",
            f"--component-parameter=gui_reference_clock_frequency={float(frequencies(definition)['reference']):.1f}",
            "--component-parameter=gui_number_of_clocks=1",
            f"--component-parameter=gui_output_clock_frequency0={float(output):.1f}",
            "--component-parameter=gui_use_locked=1",
            "--component-parameter=gui_operation_mode=direct",
            f"--part={device}", f"--system-info=DEVICE_FAMILY={FAMILY}"]


def generate(folder, identity, definition, execute, timeout, record, build, *, device=None):
    for module in (PIXEL_MODULE, SYSTEM_MODULE):
        log = folder / ("generate-" + module + ".log")
        execute(generation_command(identity, definition, module, device), folder, log, timeout, record, build)
        _verify_log(log, module)
    verify(folder, definition)


def _verify_log(log, module):
    """The generator reported an implementable PLL and exactly its two files.

    `ip-generate` prefixes every line with a timestamp, so the builder's
    line-anchored diagnostic classifier cannot see its messages; this reads them.
    """
    text = log.read_text(encoding="utf-8", errors="replace")
    diagnostics = re.findall(r"(?m)^\S+\s+(?:Error|Critical Warning|Warning):.*$", text)
    if diagnostics:
        raise ValueError("Cyclone V PLL generator diagnostic: " + diagnostics[0].strip())
    for expected in (f"{module}: Able to implement PLL with user settings",
                     f'{module}: Done "{module}" with 1 modules, 2 files'):
        if expected not in text:
            raise ValueError("Cyclone V PLL generation is not the checked result: " + expected)


def verify(folder, definition=None):
    """Every generated PLL states exactly the requested vendor parameters."""
    definition = DEFINITION if definition is None else definition
    validate(definition)
    for module in (PIXEL_MODULE, SYSTEM_MODULE):
        _verify_module(folder, definition, module)


def _verify_module(folder, definition, module):
    path = folder / (module + ".v")
    text = path.read_text(encoding="utf-8")
    values = frequencies(definition)
    expected = {"fractional_vco_multiplier": '"false"',
                "reference_clock_frequency": f'"{float(values["reference"]):.1f} MHz"',
                "operation_mode": '"direct"', "number_of_clocks": "1",
                "output_clock_frequency0": f'"{float(values[module]):.6f} MHz"',
                "phase_shift0": '"0 ps"', "duty_cycle0": "50",
                "pll_type": '"General"', "pll_subtype": '"General"'}
    # Every other output must be off, so the instance carries exactly one clock.
    for index in range(1, 18):
        expected[f"output_clock_frequency{index}"] = '"0 MHz"'
        expected[f"phase_shift{index}"] = '"0 ps"'
        expected[f"duty_cycle{index}"] = "50"
    for key, value in expected.items():
        found = re.findall(r"\.\s*" + key + r"\s*\(\s*([^,()]*?)\s*\)", text)
        if found != [value]:
            raise ValueError(f"generated PLL parameter mismatch: {key}")
    if re.search(r'`include\b|\$(?:readmemh|readmemb|fopen)\b', text):
        raise ValueError("untracked generated PLL dependency")
    if not re.search(r"module\s+" + re.escape(module) + r"\s*\(", text):
        raise ValueError("generated PLL module mismatch")
    ports = re.findall(r"(?m)^\s*(input|output)\s+wire\s+(\w+)\s*,?\s*$", text)
    if ports != [("input", "refclk"), ("input", "rst"), ("output", "outclk_0"), ("output", "locked")]:
        raise ValueError("generated PLL ports differ")
    if not re.search(r"\)\s*altera_pll_i\s*\(", text):
        raise ValueError("generated PLL instance name differs")


CONNECTIVITY_WARNING = "Warning (12241): 2 hierarchies have connectivity warnings - see the Connectivity Checks report folder"
SYNTHESIS_WARNING = "Warning (330000): Timing-Driven Synthesis is skipped because it could not initialize the timing netlist"
# The optional Altera PLL ports the generated wrapper leaves unconnected, with
# the severity the connectivity check gives each one.
CONNECTIVITY_PORTS = {
    ("fboutclk", "Output", "Info"): "Explicitly unconnected",
    ("fbclk", "Input", "Info"): "Stuck at GND",
    **{(name, "Input", "Warning"): "Declared by entity but not connected by instance. If a default value exists, it will be used.  Otherwise, the port will be connected to GND."
       for name in ("refclk1", "phase_en", "updn", "num_phase_shifts", "scanclk", "cntsel",
                    "reconfig_to_pll", "extswitch", "adjpllin", "cclk")},
    **{(name, kind, "Warning"): "Declared by entity but not connected by instance. Logic that only feeds a dangling port will be removed."
       for name, kind in (("phase_done", "Output"), ("reconfig_from_pll", "Output"), ("activeclk", "Output"),
                          ("clkbad", "Output"), ("phout", "Output"), ("lvds_clk", "Output"), ("loaden", "Output"),
                          ("extclk_out", "Output"), ("cascade_out", "Output"), ("zdbfbclk", "Bidir"))},
}


def explained_diagnostics(text, folder, definition):
    """Explain the two Cyclone V clocking diagnostics, each against its report.

    12241 counts the generated wrapper's unconnected optional Altera PLL ports.
    It is accepted only after the synthesis report's two port connectivity
    tables are found to name exactly the two PLL instances and exactly the
    optional ports the wrapper leaves open.

    330000 is the cost of the checked endpoint collections: they name the
    generated PLL output clocks, which exist in the Fitter and Timing Analyzer
    netlists but not in the pre-synthesis one, so Analysis & Synthesis cannot
    initialize a timing netlist and skips timing-driven synthesis. The Fitter
    and the Timing Analyzer read the same constraints where those clocks do
    exist; the retained four-corner slack is the timing evidence.
    """
    validate(definition)
    lines = [line.strip() for line in text.splitlines()
             if line.strip().startswith(("Warning (12241):", "Warning (330000):"))]
    if not lines:
        return []
    if sorted(set(lines)) != sorted({CONNECTIVITY_WARNING, SYNTHESIS_WARNING}) or len(lines) != 2:
        raise ValueError("Cyclone V clocking diagnostic identity or count differs")
    _verify_connectivity(folder)
    return [{"code": "12241", "text": CONNECTIVITY_WARNING,
             "reason": "The generated Altera PLL wrapper leaves the IP's optional reconfiguration, feedback and "
                       "secondary-output ports unconnected; the synthesis report names exactly those ports on "
                       "exactly the two PLL instances."},
            {"code": "330000", "text": SYNTHESIS_WARNING,
             "reason": "The checked endpoint collections name the generated PLL output clocks, which exist only "
                       "after synthesis; the Fitter and the Timing Analyzer read them against netlists that carry "
                       "those clocks, and the four-corner slack is retained."}]


def _verify_connectivity(folder):
    report = (folder / "output/design.map.rpt").read_text(encoding="cp1252")
    owners = re.findall(r'(?m)^; Port Connectivity Checks: "([^"]+)"\s*;\s*$', report)
    expected = [FIT_PIXEL.removesuffix("|general[0].gpll~FRACTIONAL_PLL"),
                FIT_SYSTEM.removesuffix("|general[0].gpll~FRACTIONAL_PLL")]
    if sorted(owners) != sorted(expected):
        raise ValueError("connectivity check owners differ")
    for owner in expected:
        lines = report[report.index(f'; Port Connectivity Checks: "{owner}"'):].splitlines()
        rows = {}
        for line in lines[1:]:
            cells = [cell.strip() for cell in line.split(";")[1:-1]]
            if len(cells) == 4 and cells[0] not in ("Port", ""):
                rows[(cells[0], cells[1], cells[2])] = cells[3]
            elif rows and line.startswith("+--"):
                break
        if rows != CONNECTIVITY_PORTS:
            raise ValueError("connectivity check port set or severity differs")


def clock_inventory(definition, reference):
    """Every STA clock row: name -> (kind, period, [duty, divide, multiply], master).

    Each PLL contributes its VCO clock and the output counter clock it divides.
    """
    rows = {"clk_reference": ("Base", reference, None, None)}
    for module, vco, output in ((SYSTEM_MODULE, SYSTEM_VCO, SYSTEM_CLOCK),
                                (PIXEL_MODULE, PIXEL_VCO, PIXEL_CLOCK)):
        multiply, divide, counter = COUNTERS[module]
        rows[vco] = ("Generated", reference * divide / multiply,
                     ["50.00", str(divide), str(multiply)], "clk_reference")
        rows[output] = ("Generated", reference * divide * counter / multiply,
                        ["50.00", str(counter), "1"], vco)
    return rows


def corner_slacks(target, corner):
    """The clock names each timing corner must also carry, beyond the checked clocks.

    Only the VCO clocks: they have a minimum pulse width check and no data paths.
    """
    return [f"{corner} Model Minimum Pulse Width '{name}'" for name in (SYSTEM_VCO, PIXEL_VCO)]


def timed_clocks(target):
    """The clocks every corner and check must report, in the order they are named."""
    return ("clk_reference", SYSTEM_CLOCK, PIXEL_CLOCK)


def lock_event_count(target):
    """Cyclone V has no vendor lock latch, so no register may lack a clock."""
    return 0


def verify_lock_event(folder, checks, top="nano_clocking_proof", *, parallel=False, extra_rows=()):
    if not parallel or extra_rows:
        raise ValueError("unsupported Cyclone V clocking composition")
    return fpga_lock_cyclonev.verify((folder / "simulation/questa/design.vo").read_text(encoding="utf-8"), checks, top)


# The fit report carries a degree sign in its junction temperature rows, so it
# is cp1252 on every host; utf-8 cannot decode it.
FIT_ENCODING = "cp1252"
FIT_EXPECTED = {
    "PLL Type": "Integer PLL", "PLL Feedback clock type": "none", "PLL Bandwidth": "Auto",
    "Reference Clock Frequency": "50.0 MHz", "Reference Clock Sourced by": "Dedicated Pin",
    "PLL Operation Mode": "Direct", "PLL Enable": "On", "PLL Fractional Division": "N/A",
    "IOPLL Self RST": "Off", "CLKIN(0) source": "clk_reference~input",
    "Duty Cycle": "50.0000", "Phase Shift": "0.000000 degrees",
    "C Counter PH Mux PRST": "0", "C Counter PRST": "1",
}


def verify_fit(folder, target):
    """Bind each fitted PLL to its wrapper instance, its counters and its clocks."""
    validate(target["pll"])
    report = (folder / "output/design.fit.rpt").read_text(encoding=FIT_ENCODING)
    blocks = _usage_blocks(report)
    if sorted(blocks) != sorted((FIT_SYSTEM, FIT_PIXEL)):
        raise ValueError("fitted PLL owners differ")
    for owner, module in ((FIT_SYSTEM, SYSTEM_MODULE), (FIT_PIXEL, PIXEL_MODULE)):
        multiply, divide, counter = COUNTERS[module]
        values = frequencies(target["pll"])
        expected = {**FIT_EXPECTED, "M Counter": str(multiply), "N Counter": str(divide),
                    "C Counter": str(counter),
                    "PLL VCO Frequency": _megahertz(values["reference"] * multiply / divide),
                    "Output Clock Frequency": _megahertz(values[module]),
                    "C Counter Odd Divider Even Duty Enable": "On" if counter % 2 else "Off"}
        for key, value in expected.items():
            if blocks[owner].get(key) != value:
                raise ValueError(f"fitted PLL configuration differs: {key}")
        if blocks[owner].get("PLL Output Counter") != owner.replace("~FRACTIONAL_PLL", "~PLL_OUTPUT_COUNTER"):
            raise ValueError("fitted PLL output counter owner differs")
    summary = (folder / "output/design.fit.summary").read_text(encoding="utf-8")
    if re.findall(r"(?m)^Total PLLs : (\d+) /", summary) != ["2"]:
        raise ValueError("fitted PLL physical resource count differs")
    _verify_clocks(folder, target)
    fpga_clocking.verify_reports(folder, "Cyclone V reset chain path missing or violated")


def _megahertz(value):
    """The fit report's frequency form: one decimal, trailing zero kept."""
    return f"{float(value):.1f} MHz"


def _usage_blocks(report):
    """The PLL Usage Summary as {fitted PLL name: {key: value}}.

    The section indents each key with dashes under the PLL it belongs to, and
    nests the output counter's rows under its own name; that name is kept as the
    `PLL Output Counter` value so its owner is checked too.
    """
    start = report.index("; PLL Usage Summary")
    end = report.index("Fitter Resource Utilization by Entity", start)
    blocks = {}
    current = None
    for line in report[start:end].splitlines():
        cells = [cell.strip() for cell in line.split(";")[1:-1]]
        if len(cells) != 2 or not cells[0] or cells[0] == "PLL Usage Summary":
            continue
        key, value = cells
        if not key.startswith("--"):
            current = blocks.setdefault(key, {})
            continue
        if current is None:
            raise ValueError("PLL usage row without an owner")
        key = key.lstrip("- ")
        if key.endswith("~PLL_OUTPUT_COUNTER"):
            key, value = "PLL Output Counter", key
        elif not value:
            # A section label such as "PLL Refclk Select"; its rows follow.
            continue
        if key in current and current[key] != value:
            raise ValueError("duplicate PLL usage row: " + key)
        current[key] = value
    return blocks


def _verify_clocks(folder, target):
    sta = (folder / "output/design.sta.rpt").read_text(encoding="utf-8")
    rows = [[cell.strip() for cell in line.split(";")[1:-1]] for line in sta.splitlines()
            if re.match(r";[^;]+;\s*(?:Base|Generated)\s*;", line)]
    reference = Fraction(target["timing"]["reference_ns"])
    wanted = clock_inventory(target["pll"], reference)
    if len(rows) != len(wanted) or {row[0] for row in rows} != set(wanted):
        raise ValueError("Cyclone V clock inventory differs")
    for row in rows:
        kind, period, ratio, master = wanted[row[0]]
        if row[1] != kind or abs(float(row[2]) - float(period)) >= 0.001:
            raise ValueError("Cyclone V clock period differs: " + row[0])
        if ratio is not None and (row[6:9] != ratio or row[14] != master):
            raise ValueError("Cyclone V clock relationship differs: " + row[0])
