"""Verilator command construction, harness main and strict transcript checks."""
import re

# Verilate-time options shared by every target. Warnings stay fatal to the
# build; nothing here demotes them. Randomized initial values replace the
# four-state checks Questa provided. --x-initial-edge is deliberately absent:
# it fires every sensitivity trigger once at initialization, even for a clock
# that is never driven, instead of only the X-to-value edges an event-driven
# simulator sees. An edge therefore fires only on an assignment that changes a
# value; a testbench asserts a time-zero asynchronous reset by an explicit
# assignment after time zero.
COMMON_OPTIONS = ("--x-assign", "unique", "--x-initial", "unique",
                  "--trace-fst", "-j", "0", "--Mdir", "obj_dir", "--prefix", "Vtop", "-o", "sim")
# Runtime plusargs: the run seed feeds both the testbench and Verilator's own
# randomization; +verilator+rand+reset+2 randomizes every uninitialized value.
WAVES = "waves/simulation.fst"
HARNESS = "sim_main.cpp"

# A Verilator diagnostic line: an optional [time] prefix, then %Warning-<CODE>,
# %Error or %Fatal. cocotb's log levels are matched as whole upper-case words.
WARNING = re.compile(r"(?m)^\s*(?:\[\d+\]\s*)?%Warning\b|\bWARNING\b")
ERROR = re.compile(r"(?m)^.*(?:(?:\[\d+\]\s*)?%(?:Error|Fatal)\b|\bERROR\b|\bCRITICAL\b).*$")
# $fatal's own stop is reported on a second line the expected failure never carries.
FATAL_STOP = re.compile(r"^%Error: \S+: Verilog \$stop$|^Aborting\.\.\.$")
# A testbench $fatal under the cocotb peer ends the simulation while the peer
# test is still running; cocotb reports that as this two-line failure. It is
# the fatal's own stop report for a driver target that expects the fatal.
PEER_STOP = (r"(?m)^\s*[\d.]+ns WARNING\s+cocotb\.regression\s+{module}\.peer failed\n"
             r"\s*cocotb\.regression\.SimFailure: cocotb expected it would shut down the simulation, "
             r"but the simulation ended prematurely\..*$\n?")


def diagnostic(output, expected_failure=None, *, peer=None):
    """Return the first problem in a Verilator build or run transcript, else None.

    Any warning is a problem. Every error line must carry the expected failure
    text when one is declared; without one, any error line is a problem. For a
    driver target whose expected fatal appears, the cocotb peer's report of
    the ended simulation is part of that fatal.
    """
    if peer and expected_failure and any(expected_failure in line for line in ERROR.findall(output)):
        output = re.sub(PEER_STOP.format(module=re.escape(peer)), "", output, count=1)
    if WARNING.search(output):
        return "unexplained simulator warning"
    for line in ERROR.findall(output):
        if expected_failure and (expected_failure in line or FATAL_STOP.match(line.strip())):
            continue
        return "unexpected simulator diagnostic"
    return None


def main_source(top):
    """The harness main: Verilator's own --main loop plus the retained FST trace.

    The testbench's $dumpfile, if any, still writes where it says; this trace
    is the harness-owned wave the record names, so every target retains one.
    A $fatal or $stop exits nonzero through Verilator's runtime; an $error that
    lets the run continue still fails through the error count.
    """
    return f"""// Generated by tools/n2m/verilator.py: harness main for {top}.
#include <memory>
#include "verilated.h"
#include "verilated_fst_c.h"
#include "Vtop.h"

int main(int argc, char** argv, char**) {{
    const std::unique_ptr<VerilatedContext> contextp{{new VerilatedContext}};
    contextp->traceEverOn(true);
    contextp->commandArgs(argc, argv);
    const std::unique_ptr<Vtop> topp{{new Vtop{{contextp.get(), ""}}}};
    VerilatedFstC trace;
    topp->trace(&trace, 99);
    trace.open("{WAVES}");
    while (!contextp->gotFinish()) {{
        topp->eval();
        trace.dump(contextp->time());
        if (!topp->eventsPending()) break;
        contextp->time(topp->nextTimeSlot());
    }}
    topp->final();
    trace.close();
    return contextp->errorCount() > 0 ? 1 : 0;
}}
"""


def commands(simulator, root, target, seed, compiler, attempt, *, python_runtime=None, fixture_tools=None):
    """Return [(argv, cwd, log, expected_exit)]: one build, one run.

    The build verilates and compiles under compiler/obj_dir; the run executes
    from the attempt so waves, Python traces and the prepared preload files
    ($readmemh and SIM_INIT_FILE paths are relative to it) land beside the record.
    """
    tool = simulator.tools["verilator"]
    sources = [simulator.path(root / source) for source in target["sources"]]
    driver = "driver" in target
    if python_runtime or target.get("preload") is not None:
        from .python_tb import prepare as prepare_fixture
        prepare_fixture(target, attempt, root, fixture_tools)
    if python_runtime:
        # cocotb's own main drives the design; a driver target keeps --timing
        # because its SystemVerilog testbench owns the clock and the checks,
        # and cocotb's loop advances to the testbench's next time slot.
        library = python_runtime["library_dir"]
        build = [tool, "--cc", "--exe", "--build", "--vpi", "--public-flat-rw",
                 *(["--timing"] if driver else []),
                 "--timescale", "1ns/1ps", *COMMON_OPTIONS,
                 "-LDFLAGS", f"-Wl,-rpath,{library} -L{library} -lcocotbvpi_verilator",
                 "--top-module", target["top"], "+incdir+" + simulator.path(root),
                 *sources, python_runtime["support"]]
        run = [str(compiler / "obj_dir/sim"), "--trace", "--trace-file", WAVES]
    else:
        harness = compiler / HARNESS
        source = main_source(target["top"])
        # A validator replays this plan against a retained attempt; an
        # identical harness is left untouched so retained artifacts stay read-only.
        if not harness.is_file() or harness.read_text(encoding="utf-8") != source:
            harness.write_text(source, encoding="utf-8")
        build = [tool, "--cc", "--exe", "--build", "--timing", *COMMON_OPTIONS,
                 "--top-module", target["top"], "+incdir+" + simulator.path(root),
                 *sources, HARNESS]
        run = [str(compiler / "obj_dir/sim")]
    run += [f"+seed={seed}", f"+verilator+seed+{seed}", "+verilator+rand+reset+2", *target["args"]]
    if driver:
        run.append("+smoke_root=" + simulator.path(root))
    return [(build, compiler, compiler / "build.log", "zero"),
            (run, attempt, attempt / "sim.log", target["expected_exit"])]
