"""Render the handheld shell bezel's checked-in tile ROM, map and palette.

The border art lives in `tools/sw/vga_bezel/directions.json` and the preview
renderer that published it. This generator evaluates the shell direction over
the 1,560 border cells outside the scaled image, folds the distinct 8x8 cells
into a tile ROM and emits one generated SystemVerilog include for the scanout's
border stage. `wiki/src/rtl/vga/BEZEL.md` owns the direction; this file owns the
encoding only.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.sw import vga_bezel  # noqa: E402  (repository-root import)

OUTPUT = Path("src/rtl/vga/n2m_vga_bezel_rom.svh")
SOURCES = (Path("tools/sw/vga_bezel/directions.json"),
           Path("tools/sw/vga_bezel/__init__.py"))
# Screen cells of the 640x480 raster; the scaled image covers whole cells only.
CELL = 8
COLUMNS, ROWS = vga_bezel.WIDTH // CELL, vga_bezel.HEIGHT // CELL
IMAGE_COLUMNS = (vga_bezel.LEFT // CELL, vga_bezel.RIGHT // CELL)
IMAGE_ROWS = (vga_bezel.TOP // CELL, vga_bezel.BOTTOM // CELL)
PALETTE_ENTRIES = 16


def border_cell(column, row):
    """A whole 8x8 screen cell outside the scaled image."""
    return not (IMAGE_COLUMNS[0] <= column < IMAGE_COLUMNS[1]
                and IMAGE_ROWS[0] <= row < IMAGE_ROWS[1])


def map_index(column, row):
    """The border-only cell number the RTL computes from the raster coordinate."""
    if not border_cell(column, row):
        raise ValueError("cell is inside the scaled image")
    above = IMAGE_ROWS[0] * COLUMNS
    side = 2 * IMAGE_COLUMNS[0]
    if row < IMAGE_ROWS[0]:
        return row * COLUMNS + column
    if row < IMAGE_ROWS[1]:
        along = column if column < IMAGE_COLUMNS[0] else IMAGE_COLUMNS[0] + column - IMAGE_COLUMNS[1]
        return above + (row - IMAGE_ROWS[0]) * side + along
    return above + (IMAGE_ROWS[1] - IMAGE_ROWS[0]) * side + (row - IMAGE_ROWS[1]) * COLUMNS + column


def shell_pixel(root):
    """The published shell direction as one 4-bit RGB triplet per screen pixel."""
    import json
    spec = json.loads((root / SOURCES[0]).read_text(encoding="utf-8"))
    draw = vga_bezel.shell(spec["shell"])

    def pixel(x, y):
        distance = vga_bezel.distance(x, y)
        if not distance:
            raise ValueError("pixel is inside the scaled image")
        red, green, blue = draw(x, y, distance)
        # The renderer shows each 4-bit DAC code as its 8-bit screen colour.
        if red % 17 or green % 17 or blue % 17:
            raise ValueError("bezel colour is not a 4-bit VGA code")
        return (red // 17, green // 17, blue // 17)
    return pixel


def encode(root):
    """Palette, distinct tiles and the border map, in first-seen order."""
    pixel = shell_pixel(root)
    palette, tiles, cells = {}, {}, []
    for row in range(ROWS):
        for column in range(COLUMNS):
            if not border_cell(column, row):
                continue
            tile = []
            for dy in range(CELL):
                for dx in range(CELL):
                    colour = pixel(CELL * column + dx, CELL * row + dy)
                    tile.append(palette.setdefault(colour, len(palette)))
            index = tiles.setdefault(tuple(tile), len(tiles))
            cells.append((map_index(column, row), index))
    if len(palette) > PALETTE_ENTRIES:
        raise ValueError("the shell bezel needs more than 16 border colours")
    order = [index for _, index in sorted(cells)]
    if [number for number, _ in sorted(cells)] != list(range(len(cells))):
        raise ValueError("border map indices are not a dense range")
    return palette, tiles, order


def rows_of(values, per_row):
    return [", ".join(values[start:start + per_row]) for start in range(0, len(values), per_row)]


def render(root):
    palette, tiles, order = encode(root)
    digest = ", ".join(f"{path.name} {hashlib.sha256((root / path).read_bytes()).hexdigest()}"
                       for path in SOURCES)
    colours = [f"12'h{red:x}{green:x}{blue:x}" for red, green, blue in palette]
    colours += ["12'h000"] * (PALETTE_ENTRIES - len(colours))
    pixels = [f"4'd{index}" for tile in tiles for index in tile]
    text = [
        "// Generated by tools/n2m/vga_bezel_sources.py; DO NOT EDIT.",
        "// Source: " + digest,
        "// The handheld shell border of wiki/src/rtl/vga/BEZEL.md, as the tile",
        "// ROM, border-cell map and colour table the scanout's border stage reads.",
        f"localparam int unsigned BEZEL_TILES = {len(tiles)};",
        f"localparam int unsigned BEZEL_CELLS = {len(order)};",
        f"localparam int unsigned BEZEL_TILE_PIXELS = {len(pixels)};",
        "localparam logic [11:0] BEZEL_PALETTE [0:%d] = '{" % (PALETTE_ENTRIES - 1),
        *[f"    {row}," for row in rows_of(colours, 8)],
        "};",
        "localparam logic [5:0] BEZEL_MAP [0:%d] = '{" % (len(order) - 1),
        *[f"    {row}," for row in rows_of([f"6'd{index}" for index in order], 16)],
        "};",
        "localparam logic [3:0] BEZEL_TILE_ROM [0:%d] = '{" % (len(pixels) - 1),
        *[f"    {row}," for row in rows_of(pixels, 16)],
        "};",
    ]
    # SystemVerilog assignment patterns take no trailing comma.
    body = "\n".join(text).replace(",\n};", "\n};") + "\n"
    return {OUTPUT: body}


def generate(root=ROOT, check=False):
    drift = []
    for path, text in render(root).items():
        target = root / path
        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != text:
                drift.append(str(path))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8", newline="\n")
    if drift:
        raise ValueError("bezel generation drift: " + ", ".join(drift))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        generate(check=args.check)
    except (ValueError, KeyError, TypeError) as error:
        parser.exit(1, f"{error}\n")
    print("PASS VGA bezel generated sources")


if __name__ == "__main__":
    main()
