"""Pinned external image checks. No network, serial port or licensed tool is used."""
from contextlib import redirect_stdout
import hashlib
import io
import json
from pathlib import Path
import shutil
import os
import sys
import tempfile
import threading
import unittest
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from n2m import generated_interfaces as abi
from n2m import profiles
from n2m.cli import main
from n2m.doctor import select_uart
from n2m.host import external
from n2m.host.external import cache_root, read_external
from n2m.host.transport import session

from test_host import DEVICE, Endpoint, ROOT


class Download:
    """Minimal urlopen stand-in; serves exactly the bytes a test wants delivered."""
    def __init__(self, payload, final=None):
        self.payload = payload
        self.final = final
        self.calls = []
        self.url = None

    def __call__(self, url, timeout=None):
        self.calls.append(url)
        # A real redirect reports the landing URL here, which may differ from the pin.
        self.url = self.final or url
        return self

    def __enter__(self):
        return self

    def __exit__(self, *error):
        return False

    def read(self, count):
        return self.payload[:count]


def fixture_image():
    """Locally generated bytes only; never a downloaded game."""
    return bytes((index * 7 + index // 128) % 256 for index in range(abi.PROFILE_ROM_BYTES))


class ExternalRomTests(unittest.TestCase):
    def setUp(self):
        parent = ROOT / 'workdir/builds/host-unit'
        parent.mkdir(parents=True, exist_ok=True)
        self.temp = tempfile.TemporaryDirectory(prefix='external ', dir=parent)
        self.addCleanup(self.temp.cleanup)
        self.folder = Path(self.temp.name)
        self.image = fixture_image()
        self.digest = hashlib.sha256(self.image).hexdigest()
        self.name = 'fixture-' + self.folder.name.rsplit(' ', 1)[-1].lower().replace('_', '-')
        # The shared cache is host-wide, so every test points it at its own folder
        # and no run touches the developer's real images.
        self.shared = self.folder / 'cache'
        variable = patch.dict(os.environ, {external.CACHE_VARIABLE: str(self.shared)})
        variable.start()
        self.addCleanup(variable.stop)
        self.cache = self.shared / self.name

    def pins(self, drop=None, **overrides):
        pin = {'url': 'https://example.invalid/' + self.name + '.gb', 'sha256': self.digest,
               'size': len(self.image), 'license': 'CC0-1.0'}
        pin.update(overrides)
        pin.pop(drop, None)
        path = self.folder / 'pins.json'
        path.write_text(json.dumps({'external_roms': {'images': {self.name: pin}}}), encoding='utf-8')
        return path

    def test_committed_pin_list_holds_no_image_bytes(self):
        manifest = json.loads((ROOT / 'tools/n2m/dependencies.json').read_text(encoding='utf-8'))
        images = manifest['external_roms']['images']
        self.assertIn('libbet', images)
        for name, pin in images.items():
            self.assertRegex(name, '[a-z0-9][a-z0-9-]{0,63}')
            self.assertTrue(str(pin['url']).startswith('https://'))
            self.assertRegex(pin['sha256'], '[0-9a-f]{64}')
            # The size is the image length of the pin's profile; the default is the direct profile.
            self.assertEqual(pin['size'], profiles.IMAGE_BYTES[pin.get('profile', profiles.DIRECT_PROFILE_NAME)])
            self.assertTrue(pin['license'])
            # A pin describes where the image lives; it never carries image bytes.
            self.assertFalse({'data', 'bytes', 'base64', 'hex'} & set(pin))
            for notice, item in pin.get('notices', {}).items():
                self.assertRegex(notice, '[A-Za-z0-9][A-Za-z0-9._-]{0,63}')
                self.assertTrue(str(item['url']).startswith('https://'))
                self.assertRegex(item['sha256'], '[0-9a-f]{64}')
                self.assertGreater(item['size'], 0)

    def test_verified_pin_is_fetched_once_and_reread_from_cache(self):
        download = Download(self.image)
        with patch('n2m.host.external.urllib.request.urlopen', download):
            image, record = read_external(ROOT, self.name, self.pins())
            self.assertEqual(image, self.image)
            self.assertEqual(record['pin'], self.name)
            self.assertEqual(record['sha256'], self.digest)
            self.assertEqual((record['size'], record['license'], record['title']), (abi.PROFILE_ROM_BYTES, 'CC0-1.0', None))
            self.assertEqual(read_external(ROOT, self.name, self.pins())[0], self.image)
            self.assertEqual(read_external(ROOT, self.name, self.pins(title='A-1 GAME'))[1]['title'], b'A-1 GAME')
            with self.assertRaisesRegex(ValueError, 'pin title must be'):
                read_external(ROOT, self.name, self.pins(title='lower'))
        self.assertEqual(len(download.calls), 1)
        self.assertEqual((self.cache / 'image.gb').read_bytes(), self.image)

    def test_offline_reads_the_cache_and_refuses_to_fetch(self):
        download = Download(self.image)
        with patch('n2m.host.external.urllib.request.urlopen', download):
            with self.assertRaisesRegex(ValueError, f'not cached: {self.name}'):
                read_external(ROOT, self.name, self.pins(), offline=True)
            self.assertFalse(self.cache.exists())
            read_external(ROOT, self.name, self.pins())
            self.assertEqual(read_external(ROOT, self.name, self.pins(), offline=True)[0], self.image)
        self.assertEqual(len(download.calls), 1)

    def test_wrong_size_wrong_hash_and_missing_pin_refuse_before_caching(self):
        cases = [({'size': 16384}, self.image, 'image size of profile dmg-direct-v1'),
                 ({'profile': 'dmg-mbc1-v1'}, self.image, 'image size of profile dmg-mbc1-v1'),
                 ({'profile': 'dmg-mbc2-v1', 'size': 65536}, self.image, 'unknown profile'),
                 ({}, self.image[:-1], 'size mismatch'),
                 ({}, self.image + b'\0', 'size mismatch'),
                 ({'sha256': '0' * 64}, self.image, 'hash mismatch'),
                 ({'drop': 'url'}, self.image, 'missing url'),
                 ({'drop': 'license'}, self.image, 'missing license'),
                 ({'url': 'http://example.invalid/image.gb'}, self.image, 'https')]
        for pin, served, expected in cases:
            with self.subTest(expected=expected):
                download = Download(served)
                with patch('n2m.host.external.urllib.request.urlopen', download):
                    with self.assertRaisesRegex(ValueError, expected):
                        read_external(ROOT, self.name, self.pins(**pin))
                self.assertFalse(self.cache.exists())
        with patch('n2m.host.external.urllib.request.urlopen', Download(self.image)):
            with self.assertRaisesRegex(ValueError, 'unknown external image pin'):
                read_external(ROOT, 'absent-pin', self.pins())
            with self.assertRaisesRegex(ValueError, 'lowercase letters'):
                read_external(ROOT, '../escape', self.pins())
        self.assertFalse(self.cache.exists())

    def test_redirect_off_https_is_refused_even_though_the_pin_is_https(self):
        download = Download(self.image, final='http://example.invalid/' + self.name + '.gb')
        with patch('n2m.host.external.urllib.request.urlopen', download):
            with self.assertRaisesRegex(ValueError, 'redirected off https'):
                read_external(ROOT, self.name, self.pins())
        self.assertEqual(download.calls, ['https://example.invalid/' + self.name + '.gb'])
        self.assertFalse(self.cache.exists())

    def test_notice_name_must_be_a_plain_file_name(self):
        notice = {'url': 'https://example.invalid/notice.txt', 'sha256': self.digest,
                  'size': len(self.image), 'license': 'CC0-1.0'}
        for bad in ('../escape', 'sub/dir', '.hidden', ''):
            with self.subTest(notice=bad):
                shutil.rmtree(self.cache, ignore_errors=True)
                with patch('n2m.host.external.urllib.request.urlopen', Download(self.image)):
                    with self.assertRaisesRegex(ValueError, 'not a plain file name'):
                        read_external(ROOT, self.name, self.pins(notices={bad: notice}))
                # The guard runs before the fetch, so no notice file is ever created.
                self.assertEqual(sorted(path.name for path in self.cache.rglob('*')), ['image.gb'])

    def test_interrupted_cache_write_leaves_no_partial_file(self):
        def interrupted(source, target):
            raise OSError('interrupted before the cache was replaced')

        with patch('n2m.host.external.urllib.request.urlopen', Download(self.image)),              patch('n2m.records.os.replace', interrupted):
            with self.assertRaises(OSError):
                read_external(ROOT, self.name, self.pins())
        self.assertEqual(list((self.cache / 'image.gb').parent.glob('*')), [])
        with patch('n2m.host.external.urllib.request.urlopen', Download(self.image)):
            self.assertEqual(read_external(ROOT, self.name, self.pins())[0], self.image)

    def test_concurrent_readers_all_get_the_verified_image(self):
        """Publishing the cache must not deny the writers or readers racing it."""
        pins = self.pins()
        start = threading.Barrier(8)
        failures = []

        def worker():
            start.wait()
            try:
                for _ in range(15):
                    self.assertEqual(read_external(ROOT, self.name, pins)[0], self.image)
            except BaseException as error:  # reported, not raised, off the main thread
                failures.append(error)

        with patch('n2m.host.external.urllib.request.urlopen', Download(self.image)):
            threads = [threading.Thread(target=worker) for _ in range(8)]
            for thread in threads:
                thread.start()
            for thread in threads:
                thread.join()
        self.assertEqual([repr(error) for error in failures], [])
        self.assertEqual((self.cache / 'image.gb').read_bytes(), self.image)
        self.assertEqual(sorted(path.name for path in self.cache.rglob('*')), ['image.gb'])

    def test_corrupt_cache_is_refused_and_never_silently_replaced(self):
        with patch('n2m.host.external.urllib.request.urlopen', Download(self.image)):
            read_external(ROOT, self.name, self.pins())
        (self.cache / 'image.gb').write_bytes(bytes(len(self.image)))
        download = Download(self.image)
        with patch('n2m.host.external.urllib.request.urlopen', download):
            with self.assertRaisesRegex(ValueError, 'hash mismatch'):
                read_external(ROOT, self.name, self.pins())
        self.assertEqual(download.calls, [])

    def test_cache_location_follows_the_variable_then_the_per_user_default(self):
        home = self.folder / 'home'
        default = Path(*external.CACHE_FOLDER)
        self.assertEqual(cache_root(ROOT, {external.CACHE_VARIABLE: str(self.folder / 'elsewhere')}), self.folder / 'elsewhere')
        # A relative variable lands under the checkout, never on an unnamed path.
        self.assertEqual(cache_root(ROOT, {external.CACHE_VARIABLE: 'workdir/shared'}), Path(ROOT).resolve() / 'workdir/shared')
        # An unset or blank variable falls through to the per-user default.
        for environment in ({external.CACHE_VARIABLE: '  ', 'XDG_CACHE_HOME': str(home / '.cache')},
                            {'XDG_CACHE_HOME': str(home / '.cache')},
                            {'HOME': str(home)}):
            self.assertEqual(cache_root(ROOT, environment), home / '.cache' / default)
        # The host's own default lies outside the checkout, so worktrees share it.
        clean = {key: value for key, value in os.environ.items() if key != external.CACHE_VARIABLE}
        self.assertNotIn(Path(ROOT).resolve(), cache_root(ROOT, clean).parents)
        self.assertEqual(cache_root(ROOT, clean).parts[-2:], external.CACHE_FOLDER)
        with patch('n2m.host.external.WINDOWS', True):
            self.assertEqual(cache_root(ROOT, {'LOCALAPPDATA': str(home / 'AppData')}), home / 'AppData' / default)

    def test_two_checkouts_share_one_verified_cache(self):
        other = self.folder / 'second-worktree'
        other.mkdir()
        pins = self.pins()
        download = Download(self.image)
        with patch('n2m.host.external.urllib.request.urlopen', download):
            self.assertEqual(read_external(ROOT, self.name, pins)[0], self.image)
        # The second checkout holds no cache of its own and never opens the network.
        with patch('n2m.host.external.urllib.request.urlopen', side_effect=AssertionError('offline')):
            self.assertEqual(read_external(other, self.name, pins, offline=True)[0], self.image)
        self.assertFalse((other / 'workdir').exists())
        self.assertEqual(len(download.calls), 1)
        # Every read verifies the shared bytes, so a corrupt cache is refused in both checkouts.
        (self.cache / 'image.gb').write_bytes(bytes(len(self.image)))
        with patch('n2m.host.external.urllib.request.urlopen', side_effect=AssertionError('offline')):
            for root in (ROOT, other):
                with self.assertRaisesRegex(ValueError, 'hash mismatch'):
                    read_external(root, self.name, pins, offline=True)

    def test_missing_pin_fails_by_name_with_the_seeding_command(self):
        with patch('n2m.host.external.urllib.request.urlopen', side_effect=AssertionError('offline')):
            with self.assertRaises(ValueError) as raised:
                read_external(ROOT, self.name, self.pins(), offline=True)
        message = str(raised.exception)
        self.assertIn(f'not cached: {self.name}', message)
        self.assertIn('python tools/build.py sw library --tag', message)
        self.assertIn(external.CACHE_VARIABLE, message)
        self.assertIn(str(self.shared), message)

    def test_a_verified_per_checkout_cache_is_adopted_and_a_corrupt_one_is_not(self):
        checkout = self.folder / 'checkout'
        legacy = checkout / external.CACHE / self.name
        legacy.mkdir(parents=True)
        (legacy / 'image.gb').write_bytes(bytes(len(self.image)))
        offline = patch('n2m.host.external.urllib.request.urlopen', side_effect=AssertionError('offline'))
        # Corrupt per-checkout bytes are never shared; the pin still fails by name.
        with offline:
            with self.assertRaisesRegex(ValueError, f'not cached: {self.name}'):
                read_external(checkout, self.name, self.pins(), offline=True)
        self.assertFalse(self.cache.exists())
        (legacy / 'image.gb').write_bytes(self.image)
        with offline:
            self.assertEqual(read_external(checkout, self.name, self.pins(), offline=True)[0], self.image)
        self.assertEqual((self.cache / 'image.gb').read_bytes(), self.image)

    def fake_session(self, endpoint):
        def opened(folder, args, state_root):
            return session(folder, args, self.folder / 'state',
                           discover=lambda folder, args: select_uart([DEVICE], args),
                           opener=lambda port: endpoint)
        return opened

    def test_cli_external_load_transmits_the_verified_image(self):
        endpoint = Endpoint()
        command = ['host', 'load', '--external', self.name, '--uart-port', 'COM92', '--json']
        with patch('n2m.host.external.PIN_FILE', str(self.pins())), \
             patch('n2m.host.external.urllib.request.urlopen', Download(self.image)), \
             patch('n2m.host.command.session', self.fake_session(endpoint)), \
             redirect_stdout(io.StringIO()) as stdout:
            self.assertEqual(main(command, ROOT), 0)
        report = json.loads(stdout.getvalue())
        self.assertEqual(report['status'], 'PASS')
        self.assertEqual(report['result']['verified_bytes'], abi.PROFILE_ROM_BYTES)
        self.assertEqual(report['external']['pin'], self.name)
        self.assertEqual(bytes(endpoint.rom), self.image)

    def test_cli_mbc1_pin_loads_a_64_kib_session_in_the_mbc1_profile(self):
        image = bytes((index * 31 + index // 256) % 256 for index in range(abi.MBC1_ROM_BYTES))
        endpoint = Endpoint()
        command = ['host', 'load', '--external', self.name, '--uart-port', 'COM92', '--json']
        pins = self.pins(profile='dmg-mbc1-v1', size=len(image), sha256=hashlib.sha256(image).hexdigest())
        with patch('n2m.host.external.PIN_FILE', str(pins)), \
             patch('n2m.host.external.urllib.request.urlopen', Download(image)), \
             patch('n2m.host.command.session', self.fake_session(endpoint)), \
             redirect_stdout(io.StringIO()) as stdout:
            self.assertEqual(main(command, ROOT), 0)
        report = json.loads(stdout.getvalue())
        self.assertEqual(report['status'], 'PASS')
        self.assertEqual(report['result']['verified_bytes'], abi.MBC1_ROM_BYTES)
        self.assertEqual((report['external']['profile'], report['external']['profile_id']), ('dmg-mbc1-v1', abi.PROFILE_MBC1_ID))
        self.assertEqual((endpoint.profile, bytes(endpoint.rom)), (abi.PROFILE_MBC1_ID, image))
        # The same 64 KiB bytes are refused for a direct-profile pin before the port opens.
        with patch('n2m.host.external.PIN_FILE', str(self.pins(size=len(image), sha256=hashlib.sha256(image).hexdigest()))), \
             patch('n2m.host.external.urllib.request.urlopen', Download(image)), \
             patch('n2m.host.command.session') as opener, redirect_stdout(io.StringIO()):
            self.assertEqual(main(command, ROOT), 1)
        opener.assert_not_called()

    def test_cli_hash_mismatch_fails_before_the_port_opens(self):
        command = ['host', 'load', '--external', self.name, '--uart-port', 'COM92', '--json']
        with patch('n2m.host.external.PIN_FILE', str(self.pins(sha256='1' * 64))), \
             patch('n2m.host.external.urllib.request.urlopen', Download(self.image)), \
             patch('n2m.host.command.session') as opener, redirect_stdout(io.StringIO()) as stdout:
            self.assertEqual(main(command, ROOT), 1)
        opener.assert_not_called()
        self.assertIn('hash mismatch', json.loads(stdout.getvalue())['error'])
        self.assertFalse(self.cache.exists())

    def test_cli_requires_exactly_one_image_source(self):
        for extra in ([], ['--package', 'p', '--external', self.name]):
            with self.subTest(extra=extra):
                with self.assertRaises(SystemExit) as raised:
                    with patch('sys.stderr', io.StringIO()):
                        main(['host', 'load', '--uart-port', 'COM92'] + extra, ROOT)
                self.assertEqual(raised.exception.code, 2)


if __name__ == '__main__':
    unittest.main()
