"""Pinned external image checks. No network, serial port or licensed tool is used."""
from contextlib import redirect_stdout
import hashlib
import io
import json
from pathlib import Path
import shutil
import sys
import tempfile
import unittest
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from n2m import generated_interfaces as abi
from n2m.cli import main
from n2m.doctor import select_uart
from n2m.host.external import read_external
from n2m.host.transport import session

from test_host import DEVICE, Endpoint, ROOT


class Download:
    """Minimal urlopen stand-in; serves exactly the bytes a test wants delivered."""
    def __init__(self, payload):
        self.payload = payload
        self.calls = []

    def __call__(self, url, timeout=None):
        self.calls.append(url)
        return self

    def __enter__(self):
        return self

    def __exit__(self, *error):
        return False

    def read(self, count):
        return self.payload[:count]


def fixture_image():
    """Locally generated bytes only; never a downloaded game."""
    return bytes((index * 7 + index // 128) % 256 for index in range(abi.PROFILE_ROM_BYTES))


class ExternalRomTests(unittest.TestCase):
    def setUp(self):
        parent = ROOT / 'workdir/builds/host-unit'
        parent.mkdir(parents=True, exist_ok=True)
        self.temp = tempfile.TemporaryDirectory(prefix='external ', dir=parent)
        self.addCleanup(self.temp.cleanup)
        self.folder = Path(self.temp.name)
        self.image = fixture_image()
        self.digest = hashlib.sha256(self.image).hexdigest()
        self.name = 'fixture-' + self.folder.name.rsplit(' ', 1)[-1].lower().replace('_', '-')
        self.cache = ROOT / 'workdir/private/external-roms' / self.name
        self.addCleanup(shutil.rmtree, self.cache, True)

    def pins(self, drop=None, **overrides):
        pin = {'url': 'https://example.invalid/' + self.name + '.gb', 'sha256': self.digest,
               'size': len(self.image), 'license': 'CC0-1.0'}
        pin.update(overrides)
        pin.pop(drop, None)
        path = self.folder / 'pins.json'
        path.write_text(json.dumps({'external_roms': {'images': {self.name: pin}}}), encoding='utf-8')
        return path

    def test_committed_pin_list_holds_no_image_bytes(self):
        manifest = json.loads((ROOT / 'tools/n2m/dependencies.json').read_text(encoding='utf-8'))
        self.assertEqual(manifest['external_roms']['images'], {})

    def test_verified_pin_is_fetched_once_and_reread_from_cache(self):
        download = Download(self.image)
        with patch('n2m.host.external.urllib.request.urlopen', download):
            image, record = read_external(ROOT, self.name, self.pins())
            self.assertEqual(image, self.image)
            self.assertEqual(record['pin'], self.name)
            self.assertEqual(record['sha256'], self.digest)
            self.assertEqual((record['size'], record['license']), (abi.PROFILE_ROM_BYTES, 'CC0-1.0'))
            self.assertEqual(read_external(ROOT, self.name, self.pins())[0], self.image)
        self.assertEqual(len(download.calls), 1)
        self.assertEqual((self.cache / 'image.gb').read_bytes(), self.image)

    def test_wrong_size_wrong_hash_and_missing_pin_refuse_before_caching(self):
        cases = [({'size': 16384}, self.image, 'direct-profile image size'),
                 ({}, self.image[:-1], 'size mismatch'),
                 ({}, self.image + b'\0', 'size mismatch'),
                 ({'sha256': '0' * 64}, self.image, 'hash mismatch'),
                 ({'drop': 'url'}, self.image, 'missing url'),
                 ({'drop': 'license'}, self.image, 'missing license'),
                 ({'url': 'http://example.invalid/image.gb'}, self.image, 'https')]
        for pin, served, expected in cases:
            with self.subTest(expected=expected):
                download = Download(served)
                with patch('n2m.host.external.urllib.request.urlopen', download):
                    with self.assertRaisesRegex(ValueError, expected):
                        read_external(ROOT, self.name, self.pins(**pin))
                self.assertFalse(self.cache.exists())
        with patch('n2m.host.external.urllib.request.urlopen', Download(self.image)):
            with self.assertRaisesRegex(ValueError, 'unknown external image pin'):
                read_external(ROOT, 'absent-pin', self.pins())
            with self.assertRaisesRegex(ValueError, 'lowercase letters'):
                read_external(ROOT, '../escape', self.pins())
        self.assertFalse(self.cache.exists())

    def test_corrupt_cache_is_refused_and_never_silently_replaced(self):
        with patch('n2m.host.external.urllib.request.urlopen', Download(self.image)):
            read_external(ROOT, self.name, self.pins())
        (self.cache / 'image.gb').write_bytes(bytes(len(self.image)))
        download = Download(self.image)
        with patch('n2m.host.external.urllib.request.urlopen', download):
            with self.assertRaisesRegex(ValueError, 'hash mismatch'):
                read_external(ROOT, self.name, self.pins())
        self.assertEqual(download.calls, [])

    def fake_session(self, endpoint):
        def opened(folder, args, state_root):
            return session(folder, args, self.folder / 'state',
                           discover=lambda folder, args: select_uart([DEVICE], args),
                           opener=lambda port: endpoint)
        return opened

    def test_cli_external_load_transmits_the_verified_image(self):
        endpoint = Endpoint()
        command = ['host', 'load', '--external', self.name, '--uart-port', 'COM92', '--json']
        with patch('n2m.host.external.PIN_FILE', str(self.pins())), \
             patch('n2m.host.external.urllib.request.urlopen', Download(self.image)), \
             patch('n2m.host.command.session', self.fake_session(endpoint)), \
             redirect_stdout(io.StringIO()) as stdout:
            self.assertEqual(main(command, ROOT), 0)
        report = json.loads(stdout.getvalue())
        self.assertEqual(report['status'], 'PASS')
        self.assertEqual(report['result']['verified_bytes'], abi.PROFILE_ROM_BYTES)
        self.assertEqual(report['external']['pin'], self.name)
        self.assertEqual(bytes(endpoint.rom), self.image)

    def test_cli_hash_mismatch_fails_before_the_port_opens(self):
        command = ['host', 'load', '--external', self.name, '--uart-port', 'COM92', '--json']
        with patch('n2m.host.external.PIN_FILE', str(self.pins(sha256='1' * 64))), \
             patch('n2m.host.external.urllib.request.urlopen', Download(self.image)), \
             patch('n2m.host.command.session') as opener, redirect_stdout(io.StringIO()) as stdout:
            self.assertEqual(main(command, ROOT), 1)
        opener.assert_not_called()
        self.assertIn('hash mismatch', json.loads(stdout.getvalue())['error'])
        self.assertFalse(self.cache.exists())

    def test_cli_requires_exactly_one_image_source(self):
        for extra in ([], ['--package', 'p', '--external', self.name]):
            with self.subTest(extra=extra):
                with self.assertRaises(SystemExit) as raised:
                    with patch('sys.stderr', io.StringIO()):
                        main(['host', 'load', '--uart-port', 'COM92'] + extra, ROOT)
                self.assertEqual(raised.exception.code, 2)


if __name__ == '__main__':
    unittest.main()
