// Generated by tools/n2m/vga_bezel_sources.py; DO NOT EDIT.
// Source: directions.json de018c1c88311b062661362aa154a985b1abac93f2e0d16276a1bf3fa40378d1, __init__.py 8ec70aa09cb48e26f209af7a864d096a16804730a17ad2e403112df811e45a15
// The shell border's colour table, read combinationally after the tile ROM.
localparam int unsigned BEZEL_TILES = 61;
localparam int unsigned BEZEL_CELLS = 1560;
localparam int unsigned BEZEL_TILE_PIXELS = 3904;
localparam logic [11:0] BEZEL_PALETTE [0:15] = '{
    12'heed, 12'hccb, 12'h000, 12'h888, 12'h555, 12'h222, 12'h411, 12'hd22,
    12'hb23, 12'h33a, 12'h728, 12'h666, 12'h000, 12'h000, 12'h000, 12'h000
};
